export type Match = {
  id: string;
  name: string;
  age: number;
  tagline?: string;
  bio?: string;
  location?: string;
  tribe?: string;
  religion?: string;
  interests: string[];
  avatar_url?: string;
  distance?: string;
  lastActive?: string;
  isActiveNow?: boolean;
  verified?: boolean;
  personalityTags?: string[];
  profileVideo?: string;
  aiScore?: number;
  region?: string;
  current_country?: string;
  location_precision?: string;
};
