export type Match = {
  id: string;
  name: string;
  age: number;
  tagline?: string;
  bio?: string;
  location?: string;
  tribe?: string;
  religion?: string;
  interests: string[];
  avatar_url?: string;
  distance?: string;
  distanceKm?: number;
  lastActive?: string;
  isActiveNow?: boolean;
  verified?: boolean;
  verification_level?: number;
  personalityTags?: string[];
  profileVideo?: string;
  compatibility?: number;
  region?: string;
  current_country?: string;
  current_country_code?: string;
  location_precision?: string;
  matchmaking_mode?: boolean;
  discoverable_in_vibes?: boolean;
};
