export type Interest = { id: string; name: string; category: string; emoji: string };
export type PromptType = 'standard' | 'guess';
export type GuessMode = 'multiple_choice' | 'free_text';
export type GuessRevealPolicy = 'never' | 'after_correct';
export type ProfilePromptAnswer = {
  id: string;
  promptKey?: string;
  promptTitle?: string | null;
  answer: string;
  promptType?: PromptType;
  guessMode?: GuessMode | null;
  guessOptions?: string[] | null;
  hintText?: string | null;
  normalizedAnswer?: string | null;
  revealPolicy?: GuessRevealPolicy | null;
  viewerGuess?: string | null;
  viewerGuessIsCorrect?: boolean | null;
  createdAt?: string;
};

export type UserProfile = {
  id: string;
  userId?: string;
  name: string;
  age: number;
  location: string;
  city?: string;
  region?: string;
  latitude?: number;
  longitude?: number;
  profilePicture: string;
  photos: string[];
  profileVideo?: string;
  profileVideoPath?: string;
  occupation: string;
  education: string;
  verified: boolean;
  bio: string;
  distance: string;
  distanceKm?: number;
  isActiveNow: boolean;
  tribe?: string;
  religion?: string;
  personalityType?: string;
  height?: string;
  lookingFor?: string;
  loveLanguage?: string;
  languages?: string[];
  currentCountry?: string;
  currentCountryCode?: string;
  exerciseFrequency?: string;
  smoking?: string;
  drinking?: string;
  hasChildren?: string;
  wantsChildren?: string;
  locationPrecision?: string;
  interests: Interest[];
  promptAnswers?: ProfilePromptAnswer[];
  compatibility: number;
  verificationLevel?: number;
};
