export type Interest = { id: string; name: string; category: string; emoji: string };

export type UserProfile = {
  id: string;
  userId?: string;
  name: string;
  age: number;
  location: string;
  city?: string;
  region?: string;
  latitude?: number;
  longitude?: number;
  profilePicture: string;
  photos: string[];
  profileVideo?: string;
  profileVideoPath?: string;
  occupation: string;
  education: string;
  verified: boolean;
  bio: string;
  distance: string;
  distanceKm?: number;
  isActiveNow: boolean;
  tribe?: string;
  religion?: string;
  personalityType?: string;
  height?: string;
  lookingFor?: string;
  loveLanguage?: string;
  languages?: string[];
  currentCountry?: string;
  currentCountryCode?: string;
  exerciseFrequency?: string;
  smoking?: string;
  drinking?: string;
  hasChildren?: string;
  wantsChildren?: string;
  locationPrecision?: string;
  interests: Interest[];
  compatibility: number;
  verificationLevel?: number;
};
