import { Colors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const createChatMediaViewerStyles = (
  screenWidth: number,
  screenHeight: number,
) => StyleSheet.create({
    imageViewerBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.9)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    imageViewerImage: {
      width: screenWidth,
      height: screenHeight * 0.8,
    },
    imageViewerCounter: {
      position: 'absolute',
      minWidth: 64,
      height: 34,
      paddingHorizontal: 12,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.46)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    imageViewerCounterText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontFamily: 'Manrope_700Bold',
      fontVariant: ['tabular-nums'],
    },
    imageViewerPrevious: {
      position: 'absolute',
      top: '50%',
      marginTop: -23,
      left: 14,
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.46)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    imageViewerNext: {
      position: 'absolute',
      top: '50%',
      marginTop: -23,
      right: 14,
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.46)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    imageViewerNavigationDisabled: {
      opacity: 0.28,
    },
    imageViewerStatus: {
      position: 'absolute',
      alignItems: 'center',
      gap: 10,
    },
    imageViewerStatusText: {
      color: Colors.light.background,
      fontSize: 14,
      fontWeight: '600',
    },
    imageViewerRetry: {
      position: 'absolute',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderRadius: 22,
      backgroundColor: 'rgba(255,255,255,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.24)',
    },
    imageViewerRetryText: {
      color: Colors.light.background,
      fontSize: 15,
      fontWeight: '700',
    },
    imageViewerCaption: {
      position: 'absolute',
      left: 24,
      right: 24,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 18,
      backgroundColor: 'rgba(5,9,13,0.72)',
    },
    imageViewerCaptionText: {
      color: '#FFFFFF',
      fontSize: 14,
      lineHeight: 20,
      fontFamily: 'Manrope_600SemiBold',
    },
    videoViewer: {
      width: screenWidth,
      height: screenHeight * 0.8,
    },
    documentViewer: {
      width: screenWidth,
      height: screenHeight * 0.8,
      backgroundColor: Colors.light.background,
    },
    imageViewerClose: {
      position: 'absolute',
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.42)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
    },
});
