import { Colors } from '@/constants/theme';
import { withAlpha } from '@/lib/chat/ui/color-utils';
import { Platform, StyleSheet } from 'react-native';

export const createChatLocationStyles = (
  theme: typeof Colors.light,
  isDark: boolean,
) => StyleSheet.create({
    locationViewerContainer: {
      flex: 1,
      backgroundColor: theme.background,
    },
    locationViewerHeader: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 56 : 28,
      left: 16,
      right: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: withAlpha(theme.background, 0.92),
      padding: 12,
      borderRadius: 16,
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 6,
    },
    locationViewerClose: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundSubtle,
    },
    locationViewerText: {
      flex: 1,
      gap: 2,
    },
    locationViewerTitle: {
      fontSize: 16,
      fontFamily: 'PlayfairDisplay_700Bold',
      color: theme.text,
    },
    locationViewerSubtitle: {
      fontSize: 12,
      fontFamily: 'Manrope_400Regular',
      color: theme.textMuted,
    },
    locationViewerFooter: {
      position: 'absolute',
      left: 16,
      right: 16,
      bottom: Platform.OS === 'ios' ? 32 : 20,
      backgroundColor: withAlpha(theme.background, 0.82),
      padding: 12,
      borderRadius: 16,
      gap: 10,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 14,
      elevation: 6,
    },
    locationViewerLiveRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    locationViewerAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: theme.backgroundSubtle,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
    },
    locationViewerActionText: {
      fontSize: 13,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.text,
    },
    locationModalContainer: {
      flex: 1,
      backgroundColor: theme.background,
    },
    locationTopBar: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 56 : 24,
      left: 16,
      right: 16,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.18 : 0.12),
      zIndex: 20,
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.15,
      shadowRadius: 18,
      elevation: 8,
    },
    locationTopContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
    },
    locationTopButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: withAlpha(theme.background, 0.6),
    },
    locationTopTitle: {
      fontSize: 16,
      fontFamily: 'PlayfairDisplay_700Bold',
      color: theme.text,
    },
    locationTopSubtitle: {
      fontSize: 12,
      fontFamily: 'Manrope_400Regular',
      color: theme.textMuted,
      marginTop: 2,
    },
    locationTopSpacer: {
      width: 36,
    },
    locationSearchWrap: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 124 : 92,
      left: 16,
      right: 16,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.16 : 0.12),
      overflow: 'hidden',
      zIndex: 19,
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.14,
      shadowRadius: 18,
      elevation: 7,
    },
    locationSearchContent: {
      height: 46,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    locationSearchInput: {
      flex: 1,
      fontSize: 14,
      fontFamily: 'Manrope_400Regular',
      color: theme.text,
    },
    locationGlass: {
      ...StyleSheet.absoluteFill,
      backgroundColor: withAlpha(theme.background, isDark ? 0.5 : 0.65),
    },
    locationSuggestionsPanel: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 176 : 144,
      left: 16,
      right: 16,
      maxHeight: 220,
      backgroundColor: withAlpha(theme.background, 0.98),
      borderRadius: 16,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
      paddingVertical: 6,
      zIndex: 18,
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 6,
    },
    locationSuggestionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    locationSuggestionText: {
      flex: 1,
      gap: 2,
    },
    locationSuggestionTitle: {
      fontSize: 13,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.text,
    },
    locationSuggestionSubtitle: {
      fontSize: 11,
      fontFamily: 'Manrope_400Regular',
      color: theme.textMuted,
    },
    locationBottomSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 24,
      backgroundColor: 'transparent',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: 1,
      borderTopColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
      overflow: 'hidden',
      zIndex: 17,
      gap: 12,
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: -10 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 10,
    },
    locationSheetContent: {
      gap: 12,
      backgroundColor: withAlpha(theme.background, isDark ? 0.2 : 0.5),
    },
    locationSheetHandle: {
      alignSelf: 'center',
      width: 46,
      height: 5,
      borderRadius: 999,
      backgroundColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
      marginBottom: 4,
    },
    locationSelectedRow: {
      gap: 4,
    },
    locationSectionTitle: {
      fontSize: 11,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.textMuted,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    locationSelectedValue: {
      fontSize: 15,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.text,
    },
    locationSelectedSubtitle: {
      fontSize: 12,
      fontFamily: 'Manrope_400Regular',
      color: theme.textMuted,
    },
    locationNearbyRow: {
      gap: 8,
    },
    locationNearbyHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    locationNearbyCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.2 : 0.1),
      backgroundColor: withAlpha(theme.background, 0.7),
      marginRight: 10,
      minWidth: 160,
      maxWidth: 220,
      shadowColor: Colors.dark.background,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 4,
    },
    locationNearbyIcon: {
      width: 30,
      height: 30,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: withAlpha(theme.tint, isDark ? 0.16 : 0.12),
    },
    locationNearbyMeta: {
      flex: 1,
      gap: 2,
    },
    locationNearbyName: {
      fontSize: 12,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.text,
    },
    locationNearbyAddress: {
      fontSize: 10,
      fontFamily: 'Manrope_400Regular',
      color: theme.textMuted,
      marginTop: 2,
    },
    locationLiveSection: {
      gap: 8,
    },
    locationPresetRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    locationPresetChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
      backgroundColor: withAlpha(theme.background, 0.6),
    },
    locationPresetChipActive: {
      backgroundColor: theme.tint,
      borderColor: theme.tint,
    },
    locationPresetText: {
      fontSize: 12,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.text,
    },
    locationPresetTextActive: {
      color: Colors.light.background,
    },
    locationLiveHint: {
      fontSize: 11,
      fontFamily: 'Manrope_400Regular',
      color: theme.textMuted,
    },
    locationErrorText: {
      fontSize: 12,
      fontFamily: 'Manrope_400Regular',
      color: '#b91c1c',
    },
    locationActionRow: {
      flexDirection: 'row',
      gap: 10,
    },
    locationGhostButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: withAlpha(theme.text, isDark ? 0.2 : 0.12),
      backgroundColor: theme.backgroundSubtle,
    },
    locationGhostText: {
      fontSize: 13,
      fontFamily: 'Manrope_600SemiBold',
      color: theme.text,
    },
    locationPrimaryButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: theme.tint,
    },
    locationPrimaryText: {
      fontSize: 13,
      fontFamily: 'Manrope_600SemiBold',
      color: Colors.light.background,
    },
    locationLoadingOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: withAlpha(theme.background, 0.92),
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    locationLoadingText: {
      fontSize: 12,
      fontFamily: 'Manrope_500Medium',
      color: theme.textMuted,
    },
});
