import { type ResponsiveMetrics } from "@/lib/responsive";
import { Platform, StyleSheet } from "react-native";

export const createPremiumOnboardingStyles = (
  responsive: ResponsiveMetrics,
  dark: boolean,
) => {
  const shellWidth = Math.max(0, responsive.contentWidth);
  const shellHorizontalPadding = responsive.compactWidth ? 18 : responsive.tablet ? 0 : 20;
  const compactCardMinHeight = responsive.compactHeight ? 232 : 340;
  const standardCardMinHeight = responsive.tablet ? 388 : compactCardMinHeight;
  const welcomeHeroMinHeight = dark
    ? (responsive.compactHeight ? 312 : 392)
    : responsive.compactHeight
      ? 270
      : Math.round(Math.min(360, Math.max(300, responsive.usableHeight * 0.34)));
  const topInsetBreathingRoom = responsive.isAndroid ? 4 : 0;
  const palette = {
    bg: dark ? "#071E22" : "#FFF7ED",
    surface: dark ? "rgba(9, 44, 48, 0.72)" : "rgba(255, 251, 246, 0.86)",
    surfaceStrong: dark ? "rgba(10, 56, 61, 0.86)" : "rgba(255, 255, 255, 0.92)",
    border: dark ? "rgba(244, 235, 221, 0.16)" : "rgba(7, 30, 34, 0.10)",
    ink: dark ? "#F4EBDD" : "#1E130F",
    muted: dark ? "rgba(244, 235, 221, 0.66)" : "rgba(30, 19, 15, 0.62)",
    accent: dark ? "#13A8A8" : "#8B5CFF",
    accent2: dark ? "#8B5CFF" : "#13A8A8",
  };

  return StyleSheet.create({
    tokens: {
      ink: { color: palette.ink },
      muted: { color: palette.muted },
      accent: { color: palette.accent },
    } as any,
    background: {
      flex: 1,
      backgroundColor: palette.bg,
    },
    safeArea: {
      flex: 1,
      paddingTop: topInsetBreathingRoom,
    },
    keyboard: {
      flex: 1,
    },
    loadingCenter: {
      alignItems: "center",
      justifyContent: "center",
    },
    progressShell: {
      height: 3,
      width: shellWidth,
      alignSelf: "center",
      marginTop: responsive.compactHeight ? 12 : 16,
      borderRadius: 999,
      overflow: "hidden",
      backgroundColor: dark ? "rgba(244,235,221,0.12)" : "rgba(30,19,15,0.08)",
    },
    progressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: palette.accent,
    },
    topBar: {
      minHeight: 48,
      width: shellWidth,
      alignSelf: "center",
      marginTop: responsive.compactHeight ? 8 : 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    backButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.08)" : "rgba(255,255,255,0.72)",
      borderWidth: 1,
      borderColor: palette.border,
    },
    backButtonPlaceholder: {
      width: 38,
    },
    stepMeta: {
      fontSize: responsive.font(10.5, { min: 10, max: 11 }),
      fontFamily: "Manrope_700Bold",
      color: palette.muted,
      letterSpacing: 1.1,
    },
    stepMetaPlaceholder: {
      width: 70,
    },
    welcomeJourneyPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      paddingHorizontal: 11,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(255,255,255,0.58)",
      borderWidth: 1,
      borderColor: palette.border,
    },
    welcomeJourneyDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: palette.accent },
    welcomeJourneyText: { color: palette.muted, fontSize: 9.5, letterSpacing: 1.1, fontFamily: "Manrope_700Bold" },
    moreButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.08)" : "rgba(255,255,255,0.38)",
    },
    skipButton: {
      minWidth: 48,
      alignItems: "flex-end",
      paddingVertical: 8,
    },
    skipText: {
      fontSize: responsive.font(10.5, { min: 10, max: 11 }),
      fontFamily: "Manrope_600SemiBold",
      color: dark ? palette.muted : "rgba(44, 34, 26, 0.58)",
    },
    scrollContent: {
      flexGrow: 1,
      width: "100%",
      maxWidth: shellWidth,
      alignSelf: "center",
      paddingHorizontal: shellHorizontalPadding,
      paddingTop: responsive.compactHeight ? 8 : 16,
      paddingBottom: responsive.compactHeight ? 18 : 24,
    },
    welcomeScrollContent: {
      paddingTop: responsive.compactHeight ? 2 : 6,
      paddingBottom: responsive.compactHeight ? 14 : 18,
    },
    eyebrow: {
      fontSize: responsive.font(11, { min: 10, max: 12 }),
      fontFamily: "Manrope_700Bold",
      letterSpacing: 1.5,
      color: palette.accent,
      marginBottom: 18,
    },
    welcomeEyebrow: {
      fontSize: responsive.font(12, { min: 11, max: 13 }),
      letterSpacing: 1.8,
      marginBottom: responsive.compactHeight ? 12 : 14,
    },
    title: {
      fontSize: responsive.font(30, { min: 25, max: 34 }),
      lineHeight: responsive.font(36, { min: 31, max: 40 }),
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      maxWidth: Math.min(shellWidth, responsive.tablet ? 420 : 360),
    },
    locationStepTitle: {
      fontSize: responsive.font(26, { min: 23, max: 29 }),
      lineHeight: responsive.font(31, { min: 28, max: 34 }),
      maxWidth: Math.min(shellWidth, responsive.tablet ? 430 : shellWidth - 4),
    },
    welcomeTitle: {
      fontSize: responsive.font(dark ? 29 : 32, { min: dark ? 25 : 29, max: dark ? 33 : 36 }),
      lineHeight: responsive.font(dark ? 35 : 36, { min: dark ? 31 : 33, max: dark ? 39 : 40 }),
      maxWidth: Math.min(shellWidth, dark ? 360 : 390),
      letterSpacing: 0,
    },
    subtitle: {
      marginTop: 12,
      marginBottom: responsive.compactHeight ? 14 : 22,
      fontSize: responsive.font(14, { min: 13, max: 15 }),
      lineHeight: 22,
      fontFamily: "Manrope_500Medium",
      color: palette.muted,
      maxWidth: Math.min(shellWidth, responsive.tablet ? 420 : 360),
    },
    locationStepSubtitle: {
      marginTop: 10,
      marginBottom: 20,
      maxWidth: Math.min(shellWidth, responsive.tablet ? 430 : shellWidth - 10),
    },
    welcomeSubtitle: {
      marginTop: 12,
      marginBottom: responsive.compactHeight ? 8 : 10,
      fontSize: responsive.font(dark ? 14 : 15.5, { min: dark ? 13 : 14, max: dark ? 15 : 17 }),
      lineHeight: responsive.font(dark ? 22 : 23, { min: dark ? 20 : 21, max: dark ? 23 : 25 }),
      color: dark ? palette.muted : "rgba(45, 38, 34, 0.68)",
      maxWidth: Math.min(shellWidth, dark ? 352 : 388),
    },
    bodyCard: {
      minHeight: standardCardMinHeight,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      overflow: "hidden",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.22 : 0.08,
      shadowRadius: 26,
      shadowOffset: { width: 0, height: 18 },
      elevation: 8,
    },
    welcomeCard: {
      minHeight: welcomeHeroMinHeight,
      borderRadius: dark ? 30 : 0,
      backgroundColor: dark ? palette.surface : "transparent",
      borderColor: dark ? palette.border : "transparent",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.24 : 0,
      shadowRadius: dark ? 34 : 0,
      shadowOffset: { width: 0, height: dark ? 24 : 0 },
      elevation: dark ? 8 : 0,
      overflow: dark ? "hidden" : "visible",
    },
    welcomeBody: {
      minHeight: welcomeHeroMinHeight,
      justifyContent: "flex-end",
    },
    heroVisual: {
      flex: 1,
      minHeight: welcomeHeroMinHeight,
      alignItems: "center",
      justifyContent: "flex-end",
    },
    welcomeAtmosphere: {
      position: "absolute",
      left: "4%",
      right: "4%",
      top: "2%",
      bottom: "2%",
      borderRadius: 999,
    },
    welcomeHalo: {
      position: "absolute",
      width: responsive.compactHeight ? 170 : 230,
      height: responsive.compactHeight ? 170 : 230,
      top: dark ? "17%" : "10%",
      borderRadius: 999,
      backgroundColor: dark ? "#16B9B4" : "#F2C866",
      shadowColor: dark ? "#16B9B4" : "#F2C866",
      shadowOpacity: 0.36,
      shadowRadius: 38,
      shadowOffset: { width: 0, height: 0 },
    },
    welcomeOrbit: {
      position: "absolute",
      zIndex: 2,
      width: responsive.compactHeight ? 216 : 292,
      height: responsive.compactHeight ? 92 : 126,
      top: dark ? "22%" : "18%",
      borderRadius: 999,
      borderWidth: 1,
      borderColor: dark ? "rgba(124,224,218,0.23)" : "rgba(193,144,40,0.22)",
      transform: [{ rotate: "-8deg" }],
    },
    welcomeOrbitDot: {
      position: "absolute",
      width: 7,
      height: 7,
      borderRadius: 4,
      top: -4,
      left: "48%",
      backgroundColor: dark ? "#78DDD7" : "#E7B94C",
      shadowColor: dark ? "#78DDD7" : "#E7B94C",
      shadowOpacity: 0.7,
      shadowRadius: 8,
    },
    welcomeLight: {
      position: "absolute",
      zIndex: 4,
      shadowColor: "#FFFFFF",
      shadowOpacity: 0.8,
      shadowRadius: 8,
    },
    heroBaseGlow: {
      position: "absolute",
      width: "48%",
      height: responsive.compactHeight ? 56 : 70,
      bottom: responsive.compactHeight ? -4 : -6,
      borderRadius: 999,
      backgroundColor: "rgba(139, 92, 255, 0.045)",
      shadowColor: "#8B5CFF",
      shadowOpacity: 0.1,
      shadowRadius: 30,
      shadowOffset: { width: 0, height: 0 },
      transform: [{ scaleX: 1.45 }],
    },
    heroImage: {
      width: dark ? "115%" : responsive.tallHeight ? "94%" : "88%",
      height: dark ? "102%" : responsive.tallHeight ? "92%" : "88%",
      marginBottom: dark ? -38 : responsive.compactHeight ? 16 : 24,
    },
    heroImageMotion: {
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "flex-end",
    },
    heroFade: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      height: dark ? 120 : 64,
    },
    welcomeStoryPanel: {
      position: "absolute",
      left: responsive.compactWidth ? 25 : 32,
      right: responsive.compactWidth ? 25 : 32,
      bottom: responsive.compactHeight ? -2 : 0,
      zIndex: 7,
      minHeight: 62,
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
      paddingHorizontal: 13,
      paddingVertical: 11,
      borderRadius: 18,
      backgroundColor: dark ? "rgba(5,30,33,0.84)" : "rgba(255,252,247,0.88)",
      borderWidth: 1,
      borderColor: dark ? "rgba(189,242,237,0.16)" : "rgba(107,77,43,0.11)",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.25 : 0.1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    welcomeInlineAction: {
      marginTop: responsive.compactHeight ? 18 : 24,
      paddingHorizontal: responsive.compactWidth ? 2 : 4,
    },
    welcomeInlineButtonWrap: {
      width: "100%",
      borderRadius: 28,
    },
    welcomeButtonGradient: {
      ...StyleSheet.absoluteFill,
      borderRadius: 28,
    },
    welcomeButtonTopHighlight: {
      position: "absolute",
      top: 1,
      left: 18,
      right: 18,
      height: 1,
      backgroundColor: "rgba(255,255,255,0.28)",
    },
    welcomeStoryIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.09)",
      borderWidth: 1,
      borderColor: dark ? "rgba(74,211,207,0.22)" : "rgba(139,92,255,0.14)",
    },
    welcomeStoryCopy: { flex: 1 },
    welcomeStoryTitle: { color: palette.ink, fontSize: responsive.font(11.5, { min: 11, max: 12.5 }), fontFamily: "Manrope_700Bold", marginBottom: 2 },
    welcomeStoryBody: { color: palette.muted, fontSize: responsive.font(9.5, { min: 9, max: 10.5 }), lineHeight: 14, fontFamily: "Manrope_500Medium" },
    fieldBlock: {
      paddingHorizontal: responsive.compactWidth ? 16 : 18,
      paddingVertical: responsive.compactHeight ? 16 : 18,
    },
    identityIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -6 : -2,
      marginBottom: responsive.compactHeight ? 10 : 16,
      minHeight: responsive.compactHeight ? 132 : 178,
    },
    aboutIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -10 : -6,
      marginBottom: responsive.compactHeight ? 8 : 12,
      minHeight: responsive.compactHeight ? 124 : 168,
    },
    occupationIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -12 : -8,
      marginBottom: responsive.compactHeight ? 8 : 12,
      minHeight: responsive.compactHeight ? 124 : 168,
    },
    occupationSelectedCard: {
      minHeight: 70,
      marginBottom: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.12)" : "rgba(139,92,255,0.08)",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    occupationSelectedLead: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    occupationSelectedIcon: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(255,255,255,0.72)",
    },
    occupationSelectedCopy: {
      flex: 1,
      minWidth: 0,
    },
    occupationSelectedEyebrow: {
      marginBottom: 3,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 10,
      letterSpacing: 1.2,
    },
    occupationSelectedTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(15, { min: 14, max: 16 }),
    },
    occupationSearch: {
      minHeight: 54,
      paddingHorizontal: 14,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    occupationSearchInput: {
      flex: 1,
      minWidth: 0,
      paddingVertical: 0,
      color: palette.ink,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 14,
    },
    occupationSectionLabel: {
      marginTop: 16,
      marginBottom: 9,
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 10,
      letterSpacing: 1.25,
    },
    occupationGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    occupationCard: {
      width: "48%",
      minHeight: responsive.compactHeight ? 58 : 64,
      paddingHorizontal: 11,
      paddingVertical: 10,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    occupationCardSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.10)",
    },
    occupationCardIcon: {
      width: 32,
      height: 32,
      borderRadius: 11,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.05)" : "rgba(255,255,255,0.78)",
    },
    occupationCardIconSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.16)" : "rgba(139,92,255,0.09)",
    },
    occupationCardText: {
      flex: 1,
      minWidth: 0,
      color: palette.ink,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(12.5, { min: 11.5, max: 13.5 }),
      lineHeight: 17,
    },
    occupationCardTextSelected: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
    },
    occupationCustomAction: {
      minHeight: 68,
      marginTop: 12,
      paddingHorizontal: 13,
      paddingVertical: 11,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.10)" : "rgba(139,92,255,0.07)",
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    occupationCustomIcon: {
      width: 34,
      height: 34,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(255,255,255,0.74)",
    },
    occupationCustomLabel: {
      marginBottom: 3,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 9.5,
      letterSpacing: 1,
    },
    occupationCustomValue: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 14,
    },
    occupationEmpty: {
      paddingVertical: 18,
      textAlign: "center",
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 13,
    },
    bioIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -10 : -6,
      marginBottom: responsive.compactHeight ? 8 : 12,
      minHeight: responsive.compactHeight ? 120 : 164,
    },
    interestIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -8 : -4,
      marginBottom: responsive.compactHeight ? 8 : 14,
      minHeight: responsive.compactHeight ? 142 : 170,
    },
    interestsMixHeader: {
      minHeight: 54,
      paddingHorizontal: 13,
      paddingVertical: 10,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.62)",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    interestsMixEyebrow: {
      marginBottom: 2,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 9.5,
      letterSpacing: 1.2,
    },
    interestsMixCount: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 13,
    },
    interestsProgressDots: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    interestsProgressDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.06)" : "rgba(45,38,34,0.05)",
    },
    interestsProgressDotFilled: {
      borderColor: "#F6C55E",
      backgroundColor: "#F6C55E",
      shadowColor: "#F6C55E",
      shadowOpacity: 0.35,
      shadowRadius: 5,
      elevation: 2,
    },
    interestsProgressDotTeal: {
      borderColor: "#13A8A8",
      backgroundColor: "#13A8A8",
    },
    interestsProgressDotPurple: {
      borderColor: "#8B5CFF",
      backgroundColor: "#8B5CFF",
    },
    interestsSelectedWrap: {
      marginTop: 10,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 7,
    },
    interestsSelectedPill: {
      minHeight: 34,
      paddingHorizontal: 10,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.12)" : "rgba(139,92,255,0.08)",
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    interestsSelectedText: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 11.5,
    },
    interestsMixHint: {
      marginTop: 8,
      paddingHorizontal: 3,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 11.5,
    },
    interestsSearch: {
      minHeight: 52,
      marginTop: 12,
      paddingHorizontal: 13,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    interestsSearchInput: {
      flex: 1,
      minWidth: 0,
      paddingVertical: 0,
      color: palette.ink,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 13.5,
    },
    interestsDirectoryHeader: {
      marginTop: 15,
      marginBottom: 9,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    interestsDirectoryLabel: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 10,
      letterSpacing: 1.2,
    },
    interestsReadyPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(19,168,168,0.12)" : "rgba(139,92,255,0.08)",
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    interestsReadyText: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 9.5,
    },
    interestsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 9,
    },
    interestTile: {
      width: "48%",
      minHeight: responsive.compactHeight ? 54 : 60,
      paddingHorizontal: 10,
      paddingVertical: 9,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    interestTileSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.09)",
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.16 : 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
    interestTileDisabled: {
      opacity: 0.38,
    },
    interestTileIcon: {
      width: 31,
      height: 31,
      borderRadius: 11,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.05)" : "rgba(255,255,255,0.78)",
    },
    interestTileIconSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.16)" : "rgba(139,92,255,0.10)",
    },
    interestTileText: {
      flex: 1,
      minWidth: 0,
      color: palette.ink,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(11.5, { min: 10.5, max: 12.5 }),
    },
    interestTileTextSelected: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
    },
    interestsEmpty: {
      paddingVertical: 24,
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
    },
    interestsEmptyText: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 12,
    },
    ghanaPlaceIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -10 : -6,
      marginBottom: responsive.compactHeight ? 12 : 18,
      minHeight: responsive.compactHeight ? 184 : 220,
    },
    globalLocationIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      minHeight: responsive.compactHeight ? 186 : 220,
      marginTop: responsive.compactHeight ? -10 : -6,
      marginBottom: responsive.compactHeight ? 4 : 8,
    },
    rootsIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -14 : -10,
      marginBottom: responsive.compactHeight ? 2 : 8,
      height: responsive.compactHeight ? 218 : 286,
      overflow: "hidden",
    },
    valuesIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -12 : -8,
      marginBottom: responsive.compactHeight ? 8 : 14,
      height: responsive.compactHeight ? 184 : 218,
      overflow: "hidden",
    },
    relationshipIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -12 : -8,
      marginBottom: responsive.compactHeight ? 8 : 14,
      height: responsive.compactHeight ? 190 : 224,
      overflow: "hidden",
    },
    preferenceIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -12 : -8,
      marginBottom: responsive.compactHeight ? 8 : 14,
      height: responsive.compactHeight ? 188 : 220,
      overflow: "hidden",
    },
    ageRangeHero: {
      minHeight: 72,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.13)" : "rgba(139,92,255,0.09)",
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.18 : 0.09,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    ageRangeHeroIcon: {
      width: 44,
      height: 44,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.15)" : "rgba(255,255,255,0.76)",
    },
    ageRangeHeroCopy: {
      flex: 1,
      minWidth: 0,
    },
    ageRangeEyebrow: {
      marginBottom: 2,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 9.5,
      letterSpacing: 1.1,
    },
    ageRangeHeroValue: {
      color: palette.ink,
      fontFamily: "PlayfairDisplay_700Bold",
      fontSize: responsive.font(24, { min: 21, max: 27 }),
    },
    ageRangeYearsPill: {
      paddingHorizontal: 9,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(255,255,255,0.7)",
    },
    ageRangeYearsText: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 10,
    },
    ageSliderCard: {
      marginTop: 12,
      paddingHorizontal: 8,
      paddingTop: 22,
      paddingBottom: 8,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
    },
    ageSliderLayout: {
      paddingVertical: 8,
    },
    ageSliderTrackArea: {
      height: 46,
      justifyContent: "center",
    },
    ageSliderTrack: {
      height: 5,
      alignSelf: "center",
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.10)" : "rgba(7,30,34,0.10)",
    },
    ageSliderFill: {
      position: "absolute",
      height: 5,
      borderRadius: 999,
      backgroundColor: palette.accent,
      shadowColor: palette.accent,
      shadowOpacity: 0.22,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
    },
    ageSliderThumb: {
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: dark ? "rgba(127,228,220,0.24)" : "rgba(139,92,255,0.26)",
      backgroundColor: dark ? "#0C2529" : "#FFFAF6",
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.12 : 0.08,
      shadowRadius: 9,
      shadowOffset: { width: 0, height: 5 },
      elevation: 5,
    },
    ageSliderThumbActive: {
      borderColor: palette.accent,
      shadowOpacity: 0.24,
      shadowRadius: 14,
      elevation: 8,
    },
    ageSliderThumbCore: {
      width: 11,
      height: 11,
      borderRadius: 6,
      backgroundColor: palette.accent,
    },
    ageSliderBubble: {
      position: "absolute",
      top: -31,
      minWidth: 48,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 13,
      alignItems: "center",
      backgroundColor: palette.accent,
      shadowColor: palette.accent,
      shadowOpacity: 0.22,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    ageSliderBubbleText: {
      color: dark ? "#071E22" : "#FFFFFF",
      fontFamily: "Manrope_700Bold",
      fontSize: 12,
    },
    ageSliderLabels: {
      marginTop: 4,
      flexDirection: "row",
      justifyContent: "space-between",
    },
    ageSliderLabel: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 10.5,
    },
    ageRangeQuickRow: {
      marginTop: 10,
      flexDirection: "row",
      gap: 8,
    },
    ageRangeQuickButton: {
      flex: 1,
      minHeight: 38,
      paddingHorizontal: 8,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.58)",
      alignItems: "center",
      justifyContent: "center",
    },
    ageRangeQuickText: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 10.5,
    },
    ageRangeReassurance: {
      marginTop: 11,
      paddingHorizontal: 4,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    ageRangeReassuranceText: {
      flex: 1,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 11,
      lineHeight: 16,
    },
    intentSectionHeader: {
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    intentSectionLabel: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 10,
      letterSpacing: 1.25,
    },
    intentChosenPill: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(19,168,168,0.12)" : "rgba(139,92,255,0.08)",
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    intentChosenText: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 9.5,
    },
    intentOptionStack: {
      gap: 9,
    },
    intentOption: {
      minHeight: responsive.compactHeight ? 64 : 72,
      paddingHorizontal: 13,
      paddingVertical: 11,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    intentOptionSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.09)",
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.18 : 0.09,
      shadowRadius: 15,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    intentOptionIcon: {
      width: 40,
      height: 40,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.05)" : "rgba(255,255,255,0.78)",
    },
    intentOptionIconSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.16)" : "rgba(139,92,255,0.10)",
    },
    intentOptionCopy: {
      flex: 1,
      minWidth: 0,
    },
    intentOptionTitle: {
      marginBottom: 3,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(14, { min: 13, max: 15 }),
    },
    intentOptionTitleSelected: {
      color: palette.accent,
    },
    intentOptionDescription: {
      color: palette.muted,
      fontFamily: "Manrope_500Medium",
      fontSize: responsive.font(11.5, { min: 10.5, max: 12.5 }),
      lineHeight: 16,
    },
    intentOptionDescriptionSelected: {
      color: dark ? "rgba(244,235,221,0.78)" : "rgba(45,38,34,0.68)",
    },
    intentReassuranceCard: {
      marginTop: 11,
      paddingHorizontal: 13,
      paddingVertical: 12,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.56)",
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    intentReassuranceIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(19,168,168,0.12)" : "rgba(139,92,255,0.08)",
    },
    intentReassuranceTitle: {
      marginBottom: 2,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 12.5,
    },
    intentReassuranceText: {
      color: palette.muted,
      fontFamily: "Manrope_500Medium",
      fontSize: 11,
      lineHeight: 16,
    },
    valuesSectionHeader: {
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    valuesSectionLabel: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 10,
      letterSpacing: 1.25,
    },
    valuesPrivatePill: {
      paddingHorizontal: 9,
      paddingVertical: 5,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.05)" : "rgba(255,255,255,0.68)",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    valuesPrivatePillText: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 10,
    },
    valuesOptionStack: {
      gap: 9,
    },
    valuesOption: {
      minHeight: responsive.compactHeight ? 60 : 66,
      paddingHorizontal: 13,
      paddingVertical: 10,
      borderRadius: 19,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    valuesOptionSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.09)",
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.16 : 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 7 },
      elevation: 2,
    },
    valuesOptionIcon: {
      width: 38,
      height: 38,
      borderRadius: 13,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.05)" : "rgba(255,255,255,0.78)",
    },
    valuesOptionIconSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.16)" : "rgba(139,92,255,0.10)",
    },
    valuesOptionTitle: {
      marginBottom: 2,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(14, { min: 13, max: 15 }),
    },
    valuesOptionTitleSelected: {
      color: palette.accent,
    },
    valuesOptionDescription: {
      color: palette.muted,
      fontFamily: "Manrope_500Medium",
      fontSize: responsive.font(11.5, { min: 10.5, max: 12.5 }),
      lineHeight: 16,
    },
    valuesOptionDescriptionSelected: {
      color: dark ? "rgba(244,235,221,0.78)" : "rgba(45,38,34,0.68)",
    },
    valuesMoreButton: {
      minHeight: 52,
      marginTop: 10,
      paddingHorizontal: 14,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.55)",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    valuesMoreLead: {
      flexDirection: "row",
      alignItems: "center",
      gap: 9,
    },
    valuesMoreText: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 13,
    },
    valuesMoreStack: {
      marginTop: 9,
    },
    valuesPrivacyNote: {
      marginTop: 12,
      paddingHorizontal: 4,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    valuesPrivacyNoteText: {
      flex: 1,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 11.5,
      lineHeight: 17,
    },
    valuesSelectedCard: {
      minHeight: 94,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.13)" : "rgba(139,92,255,0.09)",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.18 : 0.09,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 9 },
      elevation: 3,
    },
    valuesSelectedLead: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    valuesSelectedIcon: {
      width: 46,
      height: 46,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(255,255,255,0.76)",
    },
    valuesSelectedCopy: {
      flex: 1,
      minWidth: 0,
    },
    valuesSelectedEyebrow: {
      marginBottom: 3,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 9.5,
      letterSpacing: 1.1,
    },
    valuesSelectedTitle: {
      marginBottom: 2,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 16,
    },
    valuesSelectedDescription: {
      color: palette.muted,
      fontFamily: "Manrope_500Medium",
      fontSize: 11.5,
      lineHeight: 16,
    },
    valuesChangeButton: {
      paddingHorizontal: 11,
      paddingVertical: 8,
      borderRadius: 12,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(255,255,255,0.72)",
    },
    valuesChangeText: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: 11.5,
    },
    valuesPrivacyCard: {
      marginTop: 11,
      paddingHorizontal: 13,
      paddingVertical: 12,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.56)",
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
    },
    valuesPrivacyIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(19,168,168,0.12)" : "rgba(139,92,255,0.08)",
    },
    valuesPrivacyTitle: {
      marginBottom: 2,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 12.5,
    },
    valuesPrivacyText: {
      color: palette.muted,
      fontFamily: "Manrope_500Medium",
      fontSize: 11,
      lineHeight: 16,
    },
    fieldLabel: {
      fontSize: responsive.font(12, { min: 11, max: 13 }),
      fontFamily: "Manrope_700Bold",
      color: palette.muted,
      marginBottom: 8,
    },
    sectionEyebrow: {
      fontSize: responsive.font(11, { min: 10.5, max: 12 }),
      fontFamily: "Manrope_700Bold",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: palette.accent,
      marginBottom: 6,
    },
    sectionLead: {
      fontSize: responsive.font(13.5, { min: 13, max: 14.5 }),
      lineHeight: responsive.font(20, { min: 19, max: 21 }),
      fontFamily: "Manrope_600SemiBold",
      color: palette.muted,
      marginBottom: 14,
      maxWidth: 290,
    },
    spacedLabel: {
      marginTop: 18,
    },
    fieldLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 8,
    },
    optionalLabel: {
      fontSize: responsive.font(11.5, { min: 11, max: 12 }),
      fontFamily: "Manrope_700Bold",
      color: dark ? "rgba(139,92,255,0.9)" : "rgba(92, 71, 168, 0.88)",
    },
    input: {
      minHeight: 50,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(2, 18, 21, 0.42)" : "rgba(255,255,255,0.72)",
      paddingHorizontal: 14,
      fontSize: responsive.font(15, { min: 14, max: 16 }),
      fontFamily: "Manrope_600SemiBold",
      color: palette.ink,
    },
    inlineInput: {
      marginTop: 14,
    },
    citySection: {
      marginTop: 18,
      paddingTop: 18,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    citySectionIntro: {
      fontSize: responsive.font(15, { min: 14, max: 16 }),
      lineHeight: responsive.font(22, { min: 20, max: 23 }),
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      marginBottom: 12,
    },
    helperTextRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    helperText: {
      color: palette.muted,
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      lineHeight: responsive.font(18, { min: 17, max: 19 }),
      fontFamily: "Manrope_600SemiBold",
      flex: 1,
    },
    selectBoxSelected: {
      borderColor: dark ? "rgba(19,168,168,0.42)" : "rgba(19,168,168,0.36)",
      backgroundColor: dark ? "rgba(8,28,31,0.64)" : "rgba(245,255,252,0.92)",
    },
    selectValueWrap: {
      flex: 1,
      minWidth: 0,
    },
    selectMetaText: {
      marginTop: 3,
      color: palette.muted,
      fontSize: responsive.font(12, { min: 11.5, max: 13 }),
      fontFamily: "Manrope_600SemiBold",
    },
    selectClearButton: {
      width: 28,
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      marginRight: -2,
    },
    subtleNote: {
      marginTop: 10,
      color: palette.muted,
      fontSize: responsive.font(12, { min: 11.5, max: 13 }),
      lineHeight: responsive.font(17, { min: 16, max: 18 }),
      fontFamily: "Manrope_600SemiBold",
    },
    suggestionWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
    },
    suggestionChip: {
      minHeight: 36,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: dark ? "rgba(19,168,168,0.18)" : "rgba(19,168,168,0.22)",
      backgroundColor: dark ? "rgba(19,168,168,0.08)" : "rgba(19,168,168,0.10)",
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    suggestionChipSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.18)" : "rgba(19,168,168,0.14)",
    },
    suggestionChipText: {
      color: palette.ink,
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      fontFamily: "Manrope_700Bold",
    },
    suggestionChipTextSelected: {
      color: palette.accent,
    },
    inputError: {
      borderColor: "#E35D6A",
    },
    textArea: {
      minHeight: 154,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(2, 18, 21, 0.42)" : "rgba(255,255,255,0.72)",
      paddingHorizontal: 14,
      paddingVertical: 14,
      fontSize: responsive.font(14.5, { min: 13.5, max: 15.5 }),
      lineHeight: 21,
      fontFamily: "Manrope_500Medium",
      color: palette.ink,
    },
    counter: {
      alignSelf: "flex-end",
      marginTop: 8,
      fontSize: 11,
      fontFamily: "Manrope_700Bold",
      color: palette.muted,
    },
    chipWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: responsive.compactWidth ? 8 : 9,
    },
    choicePill: {
      minHeight: 44,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.76)",
      paddingHorizontal: 14,
      paddingVertical: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      maxWidth: "100%",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0 : 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
    },
    choicePillSelected: {
      backgroundColor: dark ? palette.accent : "#8B5CFF",
      borderColor: dark ? palette.accent : "#8B5CFF",
      shadowColor: dark ? palette.accent : "#8B5CFF",
      shadowOpacity: dark ? 0.18 : 0.16,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
    },
    choiceText: {
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      fontFamily: "Manrope_700Bold",
      color: palette.ink,
      maxWidth: responsive.tablet ? 260 : responsive.compactWidth ? 158 : 190,
    },
    choiceTextSelected: {
      color: dark ? "#071E22" : "#FFFFFF",
    },
    errorText: {
      marginTop: 9,
      fontSize: 12,
      lineHeight: 17,
      fontFamily: "Manrope_600SemiBold",
      color: "#E35D6A",
    },
    photoBlock: {
      paddingTop: 14,
      paddingBottom: 26,
      alignItems: "center",
      justifyContent: "center",
    },
    photoIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -8 : -4,
      marginBottom: responsive.compactHeight ? 2 : 5,
      minHeight: responsive.compactHeight ? 166 : 226,
    },
    photoSupportText: {
      marginBottom: 12,
      maxWidth: 232,
      textAlign: "center",
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      lineHeight: responsive.font(18, { min: 17, max: 19 }),
    },
    photoFrame: {
      width: responsive.compactHeight ? 172 : 202,
      height: responsive.compactHeight ? 172 : 202,
      borderRadius: 101,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      alignItems: "center",
      justifyContent: "center",
      overflow: "visible",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.16 : 0.08,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
    },
    photoFrameSelected: {
      borderColor: dark ? "rgba(19,168,168,0.54)" : "rgba(139,92,255,0.34)",
      shadowOpacity: dark ? 0.24 : 0.12,
      shadowRadius: 24,
      elevation: 6,
    },
    photoImage: {
      width: "100%",
      height: "100%",
      borderRadius: 101,
    },
    photoPlaceholder: {
      alignItems: "center",
      gap: 8,
    },
    photoPlaceholderText: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
    },
    cameraBadge: {
      position: "absolute",
      right: 12,
      bottom: 12,
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.accent,
      borderWidth: 2,
      borderColor: dark ? "#071E22" : "#FFF7ED",
    },
    changePhotoText: {
      marginTop: 16,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
    },
    photoStatusPill: {
      marginTop: 12,
      minHeight: 34,
      borderRadius: 999,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.055)" : "rgba(255,255,255,0.58)",
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    photoStatusText: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(12, { min: 11.5, max: 13 }),
    },
    selectBox: {
      minHeight: 52,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(2, 18, 21, 0.42)" : "rgba(255,255,255,0.72)",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    selectText: {
      flex: 1,
      minWidth: 0,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 14,
    },
    selectPlaceholder: {
      color: palette.muted,
    },
    stackChoices: {
      gap: 10,
      paddingHorizontal: responsive.compactWidth ? 16 : 18,
      paddingVertical: responsive.compactHeight ? 16 : 18,
    },
    storyOption: {
      minHeight: 72,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.58)",
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    storyOptionSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.10)",
    },
    storyOptionLead: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    storyOptionIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.06)" : "rgba(255,255,255,0.82)",
      borderWidth: 1,
      borderColor: palette.border,
    },
    storyOptionIconWrapSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.16)" : "rgba(139,92,255,0.12)",
    },
    storyOptionBody: {
      flex: 1,
      gap: 2,
    },
    storyOptionText: {
      flex: 1,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 13.5,
    },
    storyOptionTextSelected: {
      color: palette.accent,
    },
    storyOptionSubtext: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(11.75, { min: 11, max: 12.5 }),
      lineHeight: responsive.font(16.5, { min: 15.5, max: 17.5 }),
    },
    storyOptionSubtextSelected: {
      color: dark ? "rgba(233,243,243,0.86)" : "rgba(92, 71, 168, 0.88)",
    },
    privacyNote: {
      marginTop: 20,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    privacyText: {
      flex: 1,
      color: palette.muted,
      fontSize: 12,
      lineHeight: 17,
      fontFamily: "Manrope_600SemiBold",
    },
    rangeCard: {
      paddingHorizontal: responsive.compactWidth ? 18 : 22,
      paddingVertical: responsive.compactHeight ? 18 : 22,
    },
    ageRangeValue: {
      fontSize: responsive.font(36, { min: 31, max: 40 }),
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      marginBottom: 10,
    },
    rangeInputs: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 12,
      marginBottom: 24,
    },
    ageInput: {
      width: 74,
      height: 48,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      color: palette.ink,
      textAlign: "center",
      fontFamily: "Manrope_700Bold",
      fontSize: 17,
    },
    rangeLine: {
      flex: 1,
      height: 1,
      backgroundColor: palette.border,
    },
    mockSlider: {
      height: 34,
      borderRadius: 17,
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(30,19,15,0.045)",
    },
    mockSliderFill: {
      height: 3,
      marginHorizontal: 34,
      borderRadius: 999,
      backgroundColor: palette.accent,
    },
    sliderThumb: {
      position: "absolute",
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: palette.ink,
      borderWidth: 3,
      borderColor: palette.accent,
    },
    completeCard: {
      minHeight: 430,
      alignItems: "center",
      justifyContent: "center",
      padding: responsive.compactHeight ? 12 : 18,
    },
    completeIllustrationWrap: {
      position: "relative",
      alignItems: "center",
      marginBottom: 12,
      borderRadius: 28,
      overflow: "visible",
    },
    completeReadyBadge: {
      position: "absolute",
      bottom: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: palette.accent,
      borderWidth: 1,
      borderColor: dark ? "rgba(255,255,255,0.22)" : "rgba(255,255,255,0.55)",
      shadowColor: palette.accent,
      shadowOpacity: 0.28,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 5,
    },
    completeReadyBadgeText: { color: "#FFFFFF", fontSize: 9, letterSpacing: 1.3, fontFamily: "Manrope_700Bold" },
    completeIcon: {
      width: 86,
      height: 86,
      borderRadius: 43,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      marginBottom: 18,
    },
    completeTitle: {
      fontSize: 24,
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      marginBottom: 8,
    },
    completeBody: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      textAlign: "center",
      lineHeight: 21,
      maxWidth: 330,
    },
    completeSignalsRow: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8, marginTop: 16 },
    completeSignalPill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 999, backgroundColor: palette.surfaceStrong, borderWidth: 1, borderColor: palette.border },
    completeSignalText: { color: palette.muted, fontSize: 10, fontFamily: "Manrope_700Bold" },
    messageText: {
      marginTop: 14,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
    },
    footer: {
      width: "100%",
      maxWidth: shellWidth,
      alignSelf: "center",
      paddingHorizontal: shellHorizontalPadding,
      paddingTop: 10,
      paddingBottom: Platform.OS === "android" ? 14 : 10,
    },
    welcomeFooter: {
      paddingHorizontal: responsive.compactWidth ? 18 : 22,
      paddingTop: responsive.compactHeight ? 6 : 8,
      paddingBottom: Platform.OS === "android" ? 16 : 14,
    },
    primaryButton: {
      minHeight: 54,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.accent,
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.28 : 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    primaryButtonContent: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 },
    welcomePrimaryButton: {
      minHeight: 58,
      borderRadius: 26,
      overflow: "hidden",
      shadowOpacity: dark ? 0.18 : 0.085,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    welcomeFooterAssurance: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, marginTop: 8 },
    welcomeFooterAssuranceText: {
      color: dark ? palette.muted : "rgba(55,45,40,0.7)",
      fontSize: 9,
      lineHeight: 13,
      fontFamily: "Manrope_600SemiBold",
    },
    primaryButtonDisabled: {
      opacity: 1,
      backgroundColor: dark ? "rgba(244,235,221,0.16)" : "rgba(139,92,255,0.44)",
      shadowOpacity: 0,
      elevation: 0,
    },
    primaryButtonTextDisabled: {
      color: dark ? "rgba(244,235,221,0.56)" : "rgba(255,255,255,0.86)",
    },
    primaryButtonText: {
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(15, { min: 14, max: 17 }),
      color: dark ? "#071E22" : "#FFFFFF",
    },
    menuBackdrop: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: dark ? "rgba(0,0,0,0.42)" : "rgba(30, 19, 15, 0.20)",
      padding: 18,
    },
    signOutSheet: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "#071E22" : "#FFF9F1",
      padding: 14,
      shadowColor: "#000000",
      shadowOpacity: 0.16,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 12,
    },
    signOutSheetTitle: {
      paddingHorizontal: 6,
      paddingTop: 2,
      paddingBottom: 10,
      fontSize: 12,
      fontFamily: "Manrope_700Bold",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: palette.muted,
    },
    signOutSheetAction: {
      minHeight: 52,
      borderRadius: 16,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(30,19,15,0.045)",
    },
    signOutSheetActionText: {
      fontSize: 15,
      fontFamily: "Manrope_700Bold",
      color: palette.ink,
    },
    modalScreen: {
      flex: 1,
      backgroundColor: palette.bg,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: dark ? "rgba(2,8,10,0.52)" : "rgba(7,30,34,0.18)",
      justifyContent: "flex-end",
    },
    modalSheet: {
      flex: 1,
      justifyContent: "flex-end",
    },
    modalSheetInner: {
      flex: 1,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.bg,
      overflow: "hidden",
    },
    modalHeader: {
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    modalClose: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    modalTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 16,
    },
    modalBodyIntro: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 2,
    },
    modalBodyLead: {
      color: palette.ink,
      fontFamily: "PlayfairDisplay_700Bold",
      fontSize: responsive.font(18, { min: 17, max: 20 }),
      lineHeight: responsive.font(25, { min: 24, max: 27 }),
    },
    modalBodySupport: {
      marginTop: 6,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      lineHeight: responsive.font(18, { min: 17, max: 19 }),
    },
    searchBox: {
      margin: 16,
      minHeight: 54,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.06)" : "rgba(255,252,246,0.96)",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    searchInput: {
      flex: 1,
      color: palette.ink,
      fontFamily: "Manrope_600SemiBold",
    },
    globalCityGuidance: {
      paddingHorizontal: 16,
      paddingBottom: 10,
    },
    globalCityAttribution: {
      textAlign: "center",
      paddingVertical: 10,
    },
    cityPickerListContent: {
      paddingHorizontal: 16,
      paddingBottom: 28,
    },
    cityPickerSectionTitle: {
      marginTop: 8,
      marginBottom: 8,
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 11,
      letterSpacing: 1.1,
      textTransform: "uppercase",
    },
    cityPickerRow: {
      minHeight: 56,
      borderBottomWidth: 1,
      borderBottomColor: dark ? "rgba(244,235,221,0.08)" : "rgba(7,30,34,0.08)",
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    cityPickerRowSelected: {
      borderRadius: 16,
      paddingHorizontal: 12,
      backgroundColor: dark ? "rgba(19,168,168,0.10)" : "rgba(19,168,168,0.08)",
      borderBottomColor: "transparent",
    },
    cityPickerRowTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(14.5, { min: 14, max: 15.5 }),
    },
    cityPickerSkeletonRow: {
      minHeight: 56,
      borderBottomWidth: 1,
      borderBottomColor: dark ? "rgba(244,235,221,0.08)" : "rgba(7,30,34,0.08)",
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    cityPickerSkeletonTextWrap: {
      flex: 1,
      gap: 8,
    },
    cityPickerSkeletonTitle: {
      width: "52%",
      height: 18,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.10)" : "rgba(7,30,34,0.08)",
    },
    cityPickerSkeletonMeta: {
      width: "36%",
      height: 13,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(7,30,34,0.05)",
    },
    cityPickerSkeletonChevron: {
      width: 16,
      height: 16,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.08)" : "rgba(7,30,34,0.06)",
    },
    cityPickerQuietAction: {
      minHeight: 54,
      borderRadius: 16,
      marginTop: 14,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: dark ? "rgba(244,235,221,0.04)" : "rgba(30,19,15,0.035)",
    },
    cityPickerQuietActionText: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(13.5, { min: 13, max: 14.5 }),
    },
    countryListContent: {
      paddingHorizontal: 16,
      paddingBottom: 28,
    },
    countryRow: {
      minHeight: 54,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      paddingHorizontal: 14,
      marginBottom: 9,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    countryRowSelected: {
      borderColor: palette.accent,
    },
    countryName: {
      flex: 1,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
    },
    modalListTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    modalListMeta: {
      marginTop: 3,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 12,
    },
    countryDial: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 12,
    },
    modalEmptyState: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      paddingHorizontal: 16,
      paddingVertical: 18,
      marginTop: 4,
    },
    modalEmptyTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 14,
      marginBottom: 4,
    },
    modalEmptyBody: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 12.5,
      lineHeight: 18,
    },
  });
};
