import { type ResponsiveMetrics } from "@/lib/responsive";
import { Platform, StyleSheet } from "react-native";

export const createPremiumOnboardingStyles = (
  responsive: ResponsiveMetrics,
  dark: boolean,
) => {
  const shellWidth = Math.max(0, responsive.contentWidth);
  const shellHorizontalPadding = responsive.compactWidth ? 18 : responsive.tablet ? 0 : 20;
  const compactCardMinHeight = responsive.compactHeight ? 252 : 340;
  const standardCardMinHeight = responsive.tablet ? 388 : compactCardMinHeight;
  const topInsetBreathingRoom = responsive.isAndroid ? 4 : 0;
  const palette = {
    bg: dark ? "#071E22" : "#FFF7ED",
    surface: dark ? "rgba(9, 44, 48, 0.72)" : "rgba(255, 251, 246, 0.86)",
    surfaceStrong: dark ? "rgba(10, 56, 61, 0.86)" : "rgba(255, 255, 255, 0.92)",
    border: dark ? "rgba(244, 235, 221, 0.16)" : "rgba(7, 30, 34, 0.10)",
    ink: dark ? "#F4EBDD" : "#1E130F",
    muted: dark ? "rgba(244, 235, 221, 0.66)" : "rgba(30, 19, 15, 0.62)",
    accent: dark ? "#13A8A8" : "#8B5CFF",
    accent2: dark ? "#8B5CFF" : "#13A8A8",
  };

  return StyleSheet.create({
    tokens: {
      ink: { color: palette.ink },
      muted: { color: palette.muted },
      accent: { color: palette.accent },
    } as any,
    background: {
      flex: 1,
      backgroundColor: palette.bg,
    },
    safeArea: {
      flex: 1,
      paddingTop: topInsetBreathingRoom,
    },
    keyboard: {
      flex: 1,
    },
    loadingCenter: {
      alignItems: "center",
      justifyContent: "center",
    },
    progressShell: {
      height: 3,
      width: shellWidth,
      alignSelf: "center",
      marginTop: responsive.compactHeight ? 12 : 16,
      borderRadius: 999,
      overflow: "hidden",
      backgroundColor: dark ? "rgba(244,235,221,0.12)" : "rgba(30,19,15,0.08)",
    },
    progressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: palette.accent,
    },
    topBar: {
      minHeight: 48,
      width: shellWidth,
      alignSelf: "center",
      marginTop: responsive.compactHeight ? 8 : 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    backButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.08)" : "rgba(255,255,255,0.72)",
      borderWidth: 1,
      borderColor: palette.border,
    },
    backButtonPlaceholder: {
      width: 38,
    },
    stepMeta: {
      fontSize: responsive.font(10.5, { min: 10, max: 11 }),
      fontFamily: "Manrope_700Bold",
      color: palette.muted,
      letterSpacing: 1.1,
    },
    stepMetaPlaceholder: {
      width: 70,
    },
    moreButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.08)" : "rgba(255,255,255,0.38)",
    },
    skipButton: {
      minWidth: 48,
      alignItems: "flex-end",
      paddingVertical: 8,
    },
    skipText: {
      fontSize: responsive.font(10.5, { min: 10, max: 11 }),
      fontFamily: "Manrope_600SemiBold",
      color: dark ? palette.muted : "rgba(44, 34, 26, 0.58)",
    },
    scrollContent: {
      flexGrow: 1,
      width: "100%",
      maxWidth: shellWidth,
      alignSelf: "center",
      paddingHorizontal: shellHorizontalPadding,
      paddingTop: responsive.compactHeight ? 8 : 16,
      paddingBottom: responsive.compactHeight ? 18 : 24,
    },
    welcomeScrollContent: {
      paddingTop: responsive.compactHeight ? 4 : 10,
      paddingBottom: responsive.compactHeight ? 4 : 10,
    },
    eyebrow: {
      fontSize: responsive.font(11, { min: 10, max: 12 }),
      fontFamily: "Manrope_700Bold",
      letterSpacing: 1.5,
      color: palette.accent,
      marginBottom: 18,
    },
    welcomeEyebrow: {
      fontSize: responsive.font(12, { min: 11, max: 13 }),
      letterSpacing: 1.8,
      marginBottom: responsive.compactHeight ? 14 : 18,
    },
    title: {
      fontSize: responsive.font(30, { min: 25, max: 34 }),
      lineHeight: responsive.font(36, { min: 31, max: 40 }),
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      maxWidth: Math.min(shellWidth, responsive.tablet ? 420 : 360),
    },
    welcomeTitle: {
      fontSize: responsive.font(dark ? 30 : 35, { min: dark ? 25 : 31, max: dark ? 34 : 40 }),
      lineHeight: responsive.font(dark ? 36 : 39, { min: dark ? 31 : 35, max: dark ? 40 : 44 }),
      maxWidth: Math.min(shellWidth, dark ? 360 : 390),
      letterSpacing: 0,
    },
    subtitle: {
      marginTop: 12,
      marginBottom: 22,
      fontSize: responsive.font(14, { min: 13, max: 15 }),
      lineHeight: 22,
      fontFamily: "Manrope_500Medium",
      color: palette.muted,
      maxWidth: Math.min(shellWidth, responsive.tablet ? 420 : 360),
    },
    welcomeSubtitle: {
      marginTop: 16,
      marginBottom: responsive.compactHeight ? 12 : 16,
      fontSize: responsive.font(dark ? 14 : 17, { min: dark ? 13 : 15, max: dark ? 15 : 19 }),
      lineHeight: responsive.font(dark ? 22 : 25, { min: dark ? 20 : 22, max: dark ? 23 : 28 }),
      color: dark ? palette.muted : "rgba(45, 38, 34, 0.68)",
      maxWidth: Math.min(shellWidth, dark ? 352 : 388),
    },
    bodyCard: {
      minHeight: standardCardMinHeight,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      overflow: "hidden",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.22 : 0.08,
      shadowRadius: 26,
      shadowOffset: { width: 0, height: 18 },
      elevation: 8,
    },
    welcomeCard: {
      minHeight: dark ? (responsive.compactHeight ? 312 : 392) : (responsive.compactHeight ? 244 : 300),
      borderRadius: dark ? 30 : 0,
      backgroundColor: dark ? palette.surface : "transparent",
      borderColor: dark ? palette.border : "transparent",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.24 : 0,
      shadowRadius: dark ? 34 : 0,
      shadowOffset: { width: 0, height: dark ? 24 : 0 },
      elevation: dark ? 8 : 0,
      overflow: dark ? "hidden" : "visible",
    },
    welcomeBody: {
      minHeight: dark ? (responsive.compactHeight ? 312 : 392) : (responsive.compactHeight ? 244 : 300),
      justifyContent: "flex-end",
    },
    heroVisual: {
      flex: 1,
      minHeight: dark ? (responsive.compactHeight ? 312 : 392) : (responsive.compactHeight ? 244 : 300),
      alignItems: "center",
      justifyContent: "flex-end",
    },
    heroBaseGlow: {
      position: "absolute",
      width: "64%",
      height: responsive.compactHeight ? 86 : 110,
      bottom: responsive.compactHeight ? -18 : -20,
      borderRadius: 999,
      backgroundColor: "rgba(139, 92, 255, 0.08)",
      shadowColor: "#8B5CFF",
      shadowOpacity: 0.16,
      shadowRadius: 38,
      shadowOffset: { width: 0, height: 0 },
      transform: [{ scaleX: 1.9 }],
    },
    heroImage: {
      width: dark ? "115%" : "88%",
      height: dark ? "102%" : "92%",
      marginBottom: dark ? -38 : 0,
    },
    heroFade: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      height: dark ? 120 : 64,
    },
    fieldBlock: {
      paddingHorizontal: responsive.compactWidth ? 16 : 18,
      paddingVertical: responsive.compactHeight ? 16 : 18,
    },
    identityIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -6 : -2,
      marginBottom: responsive.compactHeight ? 10 : 16,
      minHeight: responsive.compactHeight ? 150 : 178,
    },
    aboutIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -10 : -6,
      marginBottom: responsive.compactHeight ? 8 : 12,
      minHeight: responsive.compactHeight ? 142 : 168,
    },
    occupationIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -12 : -8,
      marginBottom: responsive.compactHeight ? 8 : 12,
      minHeight: responsive.compactHeight ? 142 : 168,
    },
    bioIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -10 : -6,
      marginBottom: responsive.compactHeight ? 8 : 12,
      minHeight: responsive.compactHeight ? 138 : 164,
    },
    interestIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -8 : -4,
      marginBottom: responsive.compactHeight ? 8 : 14,
      minHeight: responsive.compactHeight ? 142 : 170,
    },
    fieldLabel: {
      fontSize: responsive.font(12, { min: 11, max: 13 }),
      fontFamily: "Manrope_700Bold",
      color: palette.muted,
      marginBottom: 8,
    },
    sectionEyebrow: {
      fontSize: responsive.font(11, { min: 10.5, max: 12 }),
      fontFamily: "Manrope_700Bold",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: palette.accent,
      marginBottom: 6,
    },
    sectionLead: {
      fontSize: responsive.font(13.5, { min: 13, max: 14.5 }),
      lineHeight: responsive.font(20, { min: 19, max: 21 }),
      fontFamily: "Manrope_600SemiBold",
      color: palette.muted,
      marginBottom: 14,
      maxWidth: 290,
    },
    spacedLabel: {
      marginTop: 18,
    },
    fieldLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 8,
    },
    optionalLabel: {
      fontSize: responsive.font(11.5, { min: 11, max: 12 }),
      fontFamily: "Manrope_700Bold",
      color: dark ? "rgba(139,92,255,0.9)" : "rgba(92, 71, 168, 0.88)",
    },
    input: {
      minHeight: 50,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(2, 18, 21, 0.42)" : "rgba(255,255,255,0.72)",
      paddingHorizontal: 14,
      fontSize: responsive.font(15, { min: 14, max: 16 }),
      fontFamily: "Manrope_600SemiBold",
      color: palette.ink,
    },
    inlineInput: {
      marginTop: 14,
    },
    citySection: {
      marginTop: 18,
      paddingTop: 18,
      borderTopWidth: 1,
      borderTopColor: palette.border,
    },
    citySectionIntro: {
      fontSize: responsive.font(15, { min: 14, max: 16 }),
      lineHeight: responsive.font(22, { min: 20, max: 23 }),
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      marginBottom: 12,
    },
    helperTextRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    helperText: {
      color: palette.muted,
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      lineHeight: responsive.font(18, { min: 17, max: 19 }),
      fontFamily: "Manrope_600SemiBold",
      flex: 1,
    },
    selectBoxSelected: {
      borderColor: dark ? "rgba(19,168,168,0.42)" : "rgba(19,168,168,0.36)",
      backgroundColor: dark ? "rgba(8,28,31,0.64)" : "rgba(245,255,252,0.92)",
    },
    selectValueWrap: {
      flex: 1,
      minWidth: 0,
    },
    selectMetaText: {
      marginTop: 3,
      color: palette.muted,
      fontSize: responsive.font(12, { min: 11.5, max: 13 }),
      fontFamily: "Manrope_600SemiBold",
    },
    selectClearButton: {
      width: 28,
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      marginRight: -2,
    },
    subtleNote: {
      marginTop: 10,
      color: palette.muted,
      fontSize: responsive.font(12, { min: 11.5, max: 13 }),
      lineHeight: responsive.font(17, { min: 16, max: 18 }),
      fontFamily: "Manrope_600SemiBold",
    },
    suggestionWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
    },
    suggestionChip: {
      minHeight: 36,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: dark ? "rgba(19,168,168,0.18)" : "rgba(19,168,168,0.22)",
      backgroundColor: dark ? "rgba(19,168,168,0.08)" : "rgba(19,168,168,0.10)",
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    suggestionChipSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.18)" : "rgba(19,168,168,0.14)",
    },
    suggestionChipText: {
      color: palette.ink,
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      fontFamily: "Manrope_700Bold",
    },
    suggestionChipTextSelected: {
      color: palette.accent,
    },
    inputError: {
      borderColor: "#E35D6A",
    },
    textArea: {
      minHeight: 154,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(2, 18, 21, 0.42)" : "rgba(255,255,255,0.72)",
      paddingHorizontal: 14,
      paddingVertical: 14,
      fontSize: responsive.font(14.5, { min: 13.5, max: 15.5 }),
      lineHeight: 21,
      fontFamily: "Manrope_500Medium",
      color: palette.ink,
    },
    counter: {
      alignSelf: "flex-end",
      marginTop: 8,
      fontSize: 11,
      fontFamily: "Manrope_700Bold",
      color: palette.muted,
    },
    chipWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: responsive.compactWidth ? 8 : 9,
    },
    choicePill: {
      minHeight: 40,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.56)",
      paddingHorizontal: 13,
      paddingVertical: 9,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      maxWidth: "100%",
    },
    choicePillSelected: {
      backgroundColor: palette.accent,
      borderColor: palette.accent,
    },
    choiceText: {
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      fontFamily: "Manrope_700Bold",
      color: palette.ink,
      maxWidth: responsive.tablet ? 260 : responsive.compactWidth ? 158 : 190,
    },
    choiceTextSelected: {
      color: dark ? "#071E22" : "#FFFFFF",
    },
    errorText: {
      marginTop: 9,
      fontSize: 12,
      lineHeight: 17,
      fontFamily: "Manrope_600SemiBold",
      color: "#E35D6A",
    },
    photoBlock: {
      paddingTop: 14,
      paddingBottom: 26,
      alignItems: "center",
      justifyContent: "center",
    },
    photoIllustrationWrap: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: responsive.compactHeight ? -8 : -4,
      marginBottom: responsive.compactHeight ? 8 : 14,
      minHeight: responsive.compactHeight ? 162 : 198,
    },
    photoSupportText: {
      marginBottom: 12,
      maxWidth: 232,
      textAlign: "center",
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      lineHeight: responsive.font(18, { min: 17, max: 19 }),
    },
    photoFrame: {
      width: responsive.compactHeight ? 172 : 202,
      height: responsive.compactHeight ? 172 : 202,
      borderRadius: 101,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      alignItems: "center",
      justifyContent: "center",
      overflow: "visible",
      shadowColor: dark ? "#000000" : "#8B5CFF",
      shadowOpacity: dark ? 0.16 : 0.08,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
    },
    photoFrameSelected: {
      borderColor: dark ? "rgba(19,168,168,0.54)" : "rgba(139,92,255,0.34)",
      shadowOpacity: dark ? 0.24 : 0.12,
      shadowRadius: 24,
      elevation: 6,
    },
    photoImage: {
      width: "100%",
      height: "100%",
      borderRadius: 101,
    },
    photoPlaceholder: {
      alignItems: "center",
      gap: 8,
    },
    photoPlaceholderText: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
    },
    cameraBadge: {
      position: "absolute",
      right: 12,
      bottom: 12,
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.accent,
      borderWidth: 2,
      borderColor: dark ? "#071E22" : "#FFF7ED",
    },
    changePhotoText: {
      marginTop: 16,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
    },
    photoStatusPill: {
      marginTop: 12,
      minHeight: 34,
      borderRadius: 999,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.055)" : "rgba(255,255,255,0.58)",
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    photoStatusText: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(12, { min: 11.5, max: 13 }),
    },
    selectBox: {
      minHeight: 52,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(2, 18, 21, 0.42)" : "rgba(255,255,255,0.72)",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    selectText: {
      flex: 1,
      minWidth: 0,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 14,
    },
    selectPlaceholder: {
      color: palette.muted,
    },
    stackChoices: {
      gap: 10,
      paddingHorizontal: responsive.compactWidth ? 16 : 18,
      paddingVertical: responsive.compactHeight ? 16 : 18,
    },
    storyOption: {
      minHeight: 52,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(255,255,255,0.58)",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    storyOptionSelected: {
      borderColor: palette.accent,
      backgroundColor: dark ? "rgba(19,168,168,0.14)" : "rgba(139,92,255,0.10)",
    },
    storyOptionText: {
      flex: 1,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 13.5,
    },
    storyOptionTextSelected: {
      color: palette.accent,
    },
    privacyNote: {
      marginTop: 20,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    privacyText: {
      flex: 1,
      color: palette.muted,
      fontSize: 12,
      lineHeight: 17,
      fontFamily: "Manrope_600SemiBold",
    },
    rangeCard: {
      paddingHorizontal: responsive.compactWidth ? 18 : 22,
      paddingVertical: responsive.compactHeight ? 18 : 22,
    },
    ageRangeValue: {
      fontSize: responsive.font(36, { min: 31, max: 40 }),
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      marginBottom: 10,
    },
    rangeInputs: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 12,
      marginBottom: 24,
    },
    ageInput: {
      width: 74,
      height: 48,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      color: palette.ink,
      textAlign: "center",
      fontFamily: "Manrope_700Bold",
      fontSize: 17,
    },
    rangeLine: {
      flex: 1,
      height: 1,
      backgroundColor: palette.border,
    },
    mockSlider: {
      height: 34,
      borderRadius: 17,
      justifyContent: "center",
      backgroundColor: dark ? "rgba(244,235,221,0.045)" : "rgba(30,19,15,0.045)",
    },
    mockSliderFill: {
      height: 3,
      marginHorizontal: 34,
      borderRadius: 999,
      backgroundColor: palette.accent,
    },
    sliderThumb: {
      position: "absolute",
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: palette.ink,
      borderWidth: 3,
      borderColor: palette.accent,
    },
    completeCard: {
      minHeight: 320,
      alignItems: "center",
      justifyContent: "center",
      padding: 22,
    },
    completeIcon: {
      width: 86,
      height: 86,
      borderRadius: 43,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surfaceStrong,
      marginBottom: 18,
    },
    completeTitle: {
      fontSize: 24,
      fontFamily: "PlayfairDisplay_700Bold",
      color: palette.ink,
      marginBottom: 8,
    },
    completeBody: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      textAlign: "center",
      lineHeight: 21,
    },
    messageText: {
      marginTop: 14,
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
    },
    footer: {
      width: "100%",
      maxWidth: shellWidth,
      alignSelf: "center",
      paddingHorizontal: shellHorizontalPadding,
      paddingTop: 10,
      paddingBottom: Platform.OS === "android" ? 14 : 10,
    },
    welcomeFooter: {
      paddingHorizontal: responsive.compactWidth ? 18 : 22,
      paddingTop: responsive.compactHeight ? 6 : 8,
      paddingBottom: Platform.OS === "android" ? 16 : 14,
    },
    primaryButton: {
      minHeight: 54,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.accent,
      shadowColor: palette.accent,
      shadowOpacity: dark ? 0.28 : 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    welcomePrimaryButton: {
      minHeight: 58,
      borderRadius: 26,
      shadowOpacity: dark ? 0.22 : 0.12,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    primaryButtonDisabled: {
      opacity: 0.62,
    },
    primaryButtonText: {
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(15, { min: 14, max: 17 }),
      color: dark ? "#071E22" : "#FFFFFF",
    },
    menuBackdrop: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: dark ? "rgba(0,0,0,0.42)" : "rgba(30, 19, 15, 0.20)",
      padding: 18,
    },
    signOutSheet: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "#071E22" : "#FFF9F1",
      padding: 14,
      shadowColor: "#000000",
      shadowOpacity: 0.16,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 14 },
      elevation: 12,
    },
    signOutSheetTitle: {
      paddingHorizontal: 6,
      paddingTop: 2,
      paddingBottom: 10,
      fontSize: 12,
      fontFamily: "Manrope_700Bold",
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: palette.muted,
    },
    signOutSheetAction: {
      minHeight: 52,
      borderRadius: 16,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(30,19,15,0.045)",
    },
    signOutSheetActionText: {
      fontSize: 15,
      fontFamily: "Manrope_700Bold",
      color: palette.ink,
    },
    modalScreen: {
      flex: 1,
      backgroundColor: palette.bg,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: dark ? "rgba(2,8,10,0.52)" : "rgba(7,30,34,0.18)",
      justifyContent: "flex-end",
    },
    modalSheet: {
      flex: 1,
      justifyContent: "flex-end",
    },
    modalSheetInner: {
      flex: 1,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.bg,
      overflow: "hidden",
    },
    modalHeader: {
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    modalClose: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    modalTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 16,
    },
    modalBodyIntro: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 2,
    },
    modalBodyLead: {
      color: palette.ink,
      fontFamily: "PlayfairDisplay_700Bold",
      fontSize: responsive.font(18, { min: 17, max: 20 }),
      lineHeight: responsive.font(25, { min: 24, max: 27 }),
    },
    modalBodySupport: {
      marginTop: 6,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: responsive.font(12.5, { min: 12, max: 13.5 }),
      lineHeight: responsive.font(18, { min: 17, max: 19 }),
    },
    searchBox: {
      margin: 16,
      minHeight: 54,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: dark ? "rgba(244,235,221,0.06)" : "rgba(255,252,246,0.96)",
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    searchInput: {
      flex: 1,
      color: palette.ink,
      fontFamily: "Manrope_600SemiBold",
    },
    cityPickerListContent: {
      paddingHorizontal: 16,
      paddingBottom: 28,
    },
    cityPickerSectionTitle: {
      marginTop: 8,
      marginBottom: 8,
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 11,
      letterSpacing: 1.1,
      textTransform: "uppercase",
    },
    cityPickerRow: {
      minHeight: 56,
      borderBottomWidth: 1,
      borderBottomColor: dark ? "rgba(244,235,221,0.08)" : "rgba(7,30,34,0.08)",
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    cityPickerRowSelected: {
      borderRadius: 16,
      paddingHorizontal: 12,
      backgroundColor: dark ? "rgba(19,168,168,0.10)" : "rgba(19,168,168,0.08)",
      borderBottomColor: "transparent",
    },
    cityPickerRowTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(14.5, { min: 14, max: 15.5 }),
    },
    cityPickerSkeletonRow: {
      minHeight: 56,
      borderBottomWidth: 1,
      borderBottomColor: dark ? "rgba(244,235,221,0.08)" : "rgba(7,30,34,0.08)",
      paddingVertical: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    cityPickerSkeletonTextWrap: {
      flex: 1,
      gap: 8,
    },
    cityPickerSkeletonTitle: {
      width: "52%",
      height: 18,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.10)" : "rgba(7,30,34,0.08)",
    },
    cityPickerSkeletonMeta: {
      width: "36%",
      height: 13,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.07)" : "rgba(7,30,34,0.05)",
    },
    cityPickerSkeletonChevron: {
      width: 16,
      height: 16,
      borderRadius: 999,
      backgroundColor: dark ? "rgba(244,235,221,0.08)" : "rgba(7,30,34,0.06)",
    },
    cityPickerQuietAction: {
      minHeight: 54,
      borderRadius: 16,
      marginTop: 14,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: dark ? "rgba(244,235,221,0.04)" : "rgba(30,19,15,0.035)",
    },
    cityPickerQuietActionText: {
      color: palette.accent,
      fontFamily: "Manrope_700Bold",
      fontSize: responsive.font(13.5, { min: 13, max: 14.5 }),
    },
    countryListContent: {
      paddingHorizontal: 16,
      paddingBottom: 28,
    },
    countryRow: {
      minHeight: 54,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      paddingHorizontal: 14,
      marginBottom: 9,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    countryRowSelected: {
      borderColor: palette.accent,
    },
    countryName: {
      flex: 1,
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
    },
    modalListTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    modalListMeta: {
      marginTop: 3,
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 12,
    },
    countryDial: {
      color: palette.muted,
      fontFamily: "Manrope_700Bold",
      fontSize: 12,
    },
    modalEmptyState: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.surface,
      paddingHorizontal: 16,
      paddingVertical: 18,
      marginTop: 4,
    },
    modalEmptyTitle: {
      color: palette.ink,
      fontFamily: "Manrope_700Bold",
      fontSize: 14,
      marginBottom: 4,
    },
    modalEmptyBody: {
      color: palette.muted,
      fontFamily: "Manrope_600SemiBold",
      fontSize: 12.5,
      lineHeight: 18,
    },
  });
};
