-- Tighten profile-interest notification cadence and make delivery copy
-- explicitly tiered for Free, Silver, and Gold.

create table if not exists public.profile_interest_notification_deliveries (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null references auth.users (id) on delete cascade,
  actor_profile_id uuid references public.profiles (id) on delete set null,
  target_profile_id uuid not null references public.profiles (id) on delete cascade,
  signal_group text not null,
  signal_type text not null,
  audience_plan text not null,
  dedupe_scope text not null default 'actor',
  delivered_at timestamptz not null default timezone('utc'::text, now()),
  constraint profile_interest_notification_deliveries_signal_group_check
    check (signal_group in ('save', 'intro', 'intent', 'repeat_visit')),
  constraint profile_interest_notification_deliveries_signal_type_check
    check (signal_type in ('profile_saved', 'intro_played', 'intro_completed', 'intent_opened', 'profile_opened', 'full_profile_opened')),
  constraint profile_interest_notification_deliveries_plan_check
    check (audience_plan in ('FREE', 'SILVER', 'GOLD')),
  constraint profile_interest_notification_deliveries_scope_check
    check (dedupe_scope in ('actor', 'global'))
);

alter table public.profile_interest_notification_deliveries enable row level security;

create index if not exists idx_profile_interest_notification_deliveries_lookup
  on public.profile_interest_notification_deliveries (recipient_user_id, signal_group, delivered_at desc);

create index if not exists idx_profile_interest_notification_deliveries_actor
  on public.profile_interest_notification_deliveries (recipient_user_id, actor_profile_id, delivered_at desc)
  where actor_profile_id is not null;

create or replace function public.rpc_log_vibes_event(
  p_viewer_profile_id uuid,
  p_target_profile_id uuid,
  p_segment text default 'for_you',
  p_event_type text default 'card_seen',
  p_position integer default null,
  p_dwell_ms integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, private, pg_catalog
as $$
declare
  v_viewer_user_id uuid;
  v_target_user_id uuid;
  v_viewer_name text;
  v_viewer_avatar text;
  v_target_plan text := 'FREE';
  v_segment text := coalesce(nullif(btrim(p_segment), ''), 'for_you');
  v_event_type text := coalesce(nullif(btrim(p_event_type), ''), 'card_seen');
  v_throttle interval;
  v_has_inbox_items boolean := to_regclass('public.inbox_items') is not null;
  v_actor_label text := 'Someone';
  v_identity_revealed boolean := false;
  v_pref_inapp_enabled boolean := true;
  v_pref_push_enabled boolean := true;
  v_pref_profile_interest boolean := true;
  v_inbox_allowed boolean := false;
  v_push_allowed boolean := false;
  v_delivered boolean := false;
  v_recent_delivery_exists boolean := false;
  v_signal_group text;
  v_signal_dedupe_scope text := 'actor';
  v_signal_dedupe_window interval := interval '6 hours';
  v_notification_title text;
  v_notification_body text;
  v_notification_actor_id uuid;
  v_notification_metadata jsonb;
  v_push_title text;
  v_push_body text;
  v_push_payload jsonb;
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if v_segment not in ('for_you', 'nearby', 'active_now') then
    raise exception 'invalid_vibes_segment';
  end if;

  if v_event_type not in (
    'card_seen', 'profile_opened', 'full_profile_opened', 'intro_played',
    'intro_completed', 'profile_saved', 'profile_unsaved', 'pass', 'like',
    'signal_opened', 'signal_sent', 'intent_opened', 'intent_sent', 'undo'
  ) then
    raise exception 'invalid_vibes_event_type';
  end if;

  if p_viewer_profile_id is null
    or p_target_profile_id is null
    or p_viewer_profile_id = p_target_profile_id then
    return false;
  end if;

  select profile.user_id, profile.full_name, profile.avatar_url
    into v_viewer_user_id, v_viewer_name, v_viewer_avatar
  from public.profiles profile
  where profile.id = p_viewer_profile_id
    and profile.deleted_at is null
  limit 1;

  if v_viewer_user_id is null or v_viewer_user_id <> auth.uid() then
    raise exception 'viewer profile does not belong to authenticated user' using errcode = '42501';
  end if;

  select profile.user_id
    into v_target_user_id
  from public.profiles profile
  where profile.id = p_target_profile_id
    and profile.deleted_at is null
  limit 1;

  if v_target_user_id is null then
    return false;
  end if;

  v_target_plan := coalesce(public.get_active_subscription_plan(v_target_user_id)::text, 'FREE');
  if v_target_plan not in ('FREE', 'SILVER', 'GOLD') then
    v_target_plan := 'FREE';
  end if;

  if exists (
    select 1
    from public.blocks block_row
    where (block_row.blocker_id = v_viewer_user_id and block_row.blocked_id = v_target_user_id)
       or (block_row.blocker_id = v_target_user_id and block_row.blocked_id = v_viewer_user_id)
  ) then
    return false;
  end if;

  v_throttle := case
    when v_event_type = 'card_seen' then interval '6 hours'
    when v_event_type in ('profile_opened', 'full_profile_opened') then interval '30 minutes'
    when v_event_type in ('intro_played', 'intro_completed', 'intent_opened') then interval '6 hours'
    when v_event_type in ('profile_saved', 'profile_unsaved') then null
    else interval '2 minutes'
  end;

  if v_throttle is not null and exists (
    select 1
    from public.vibes_events event_row
    where event_row.viewer_profile_id = p_viewer_profile_id
      and event_row.target_profile_id = p_target_profile_id
      and event_row.event_type = v_event_type
      and event_row.segment = v_segment
      and event_row.created_at > timezone('utc'::text, now()) - v_throttle
  ) then
    return false;
  end if;

  insert into public.vibes_events (
    viewer_user_id,
    viewer_profile_id,
    target_profile_id,
    target_user_id,
    segment,
    event_type,
    position,
    dwell_ms,
    metadata
  )
  values (
    v_viewer_user_id,
    p_viewer_profile_id,
    p_target_profile_id,
    v_target_user_id,
    v_segment,
    v_event_type,
    p_position,
    greatest(coalesce(p_dwell_ms, 0), 0),
    coalesce(p_metadata, '{}'::jsonb)
  );

  v_signal_group := case
    when v_event_type = 'profile_saved' then 'save'
    when v_event_type in ('intro_played', 'intro_completed') then 'intro'
    when v_event_type = 'intent_opened' then 'intent'
    when v_event_type in ('profile_opened', 'full_profile_opened')
      and exists (
        select 1
        from public.vibes_events previous_event
        where previous_event.viewer_profile_id = p_viewer_profile_id
          and previous_event.target_profile_id = p_target_profile_id
          and previous_event.event_type in ('profile_opened', 'full_profile_opened')
          and previous_event.created_at < timezone('utc'::text, now()) - interval '30 minutes'
          and previous_event.created_at > timezone('utc'::text, now()) - interval '30 days'
      )
      then 'repeat_visit'
    else null
  end;

  if v_signal_group is null then
    return true;
  end if;

  v_signal_dedupe_scope := case
    when v_signal_group = 'repeat_visit' then 'global'
    else 'actor'
  end;

  v_signal_dedupe_window := case
    when v_signal_group = 'repeat_visit' then interval '12 hours'
    when v_signal_group = 'intro' then interval '8 hours'
    when v_signal_group = 'intent' then interval '6 hours'
    when v_signal_group = 'save' then interval '4 hours'
    else interval '6 hours'
  end;

  select
    coalesce(prefs.inapp_enabled, true),
    coalesce(prefs.push_enabled, true),
    coalesce(prefs.profile_interest, true)
    into v_pref_inapp_enabled, v_pref_push_enabled, v_pref_profile_interest
  from public.notification_prefs prefs
  where prefs.user_id = v_target_user_id
  limit 1;

  if not found then
    v_pref_inapp_enabled := true;
    v_pref_push_enabled := true;
    v_pref_profile_interest := true;
  end if;

  v_inbox_allowed := v_has_inbox_items and v_pref_inapp_enabled and v_pref_profile_interest;
  v_push_allowed := v_pref_push_enabled and v_pref_profile_interest and not public.is_quiet_hours(v_target_user_id);

  if not v_inbox_allowed and not v_push_allowed then
    return true;
  end if;

  select exists (
    select 1
    from public.profile_interest_notification_deliveries delivery
    where delivery.recipient_user_id = v_target_user_id
      and delivery.signal_group = v_signal_group
      and delivery.delivered_at > timezone('utc'::text, now()) - v_signal_dedupe_window
      and (
        v_signal_dedupe_scope = 'global'
        or delivery.actor_profile_id = p_viewer_profile_id
      )
  )
    into v_recent_delivery_exists;

  if v_recent_delivery_exists then
    return true;
  end if;

  v_actor_label := coalesce(nullif(btrim(v_viewer_name), ''), 'Someone');
  v_identity_revealed := v_target_plan in ('SILVER', 'GOLD');
  v_notification_actor_id := case when v_identity_revealed then p_viewer_profile_id else null end;

  v_notification_title := case
    when v_identity_revealed then v_actor_label
    else 'Profile Interest'
  end;

  v_notification_body := case
    when v_target_plan = 'FREE' then
      case v_signal_group
        when 'save' then 'Someone saved your profile. Upgrade to see who it is.'
        when 'intro' then 'Someone spent time with your intro video. Upgrade to see who it is.'
        when 'intent' then 'Someone opened your Intent card. Upgrade to see who it is.'
        when 'repeat_visit' then 'Someone revisited your profile. Upgrade to see who it is.'
        else null
      end
    when v_target_plan = 'GOLD' then
      case
        when v_signal_group = 'save' then 'Saved your profile. Open Profile Interest for the full signal story.'
        when v_event_type = 'intro_completed' then 'Finished your intro video. Open Profile Interest for the full signal story.'
        when v_signal_group = 'intro' then 'Spent time with your intro video. Open Profile Interest for the full signal story.'
        when v_signal_group = 'intent' then 'Opened your Intent card. Open Profile Interest for the full signal story.'
        when v_signal_group = 'repeat_visit' then 'Came back to your profile. Open Profile Interest for the full signal story.'
        else null
      end
    else
      case
        when v_signal_group = 'save' then 'Saved your profile.'
        when v_event_type = 'intro_completed' then 'Finished your intro video.'
        when v_signal_group = 'intro' then 'Spent time with your intro video.'
        when v_signal_group = 'intent' then 'Opened your Intent card.'
        when v_signal_group = 'repeat_visit' then 'Came back to your profile.'
        else null
      end
  end;

  v_push_title := case
    when v_identity_revealed then v_actor_label
    else 'Profile Interest'
  end;

  v_push_body := case
    when v_identity_revealed then
      case
        when v_signal_group = 'save' then v_actor_label || ' saved your profile.'
        when v_event_type = 'intro_completed' then v_actor_label || ' finished your intro video.'
        when v_signal_group = 'intro' then v_actor_label || ' spent time with your intro video.'
        when v_signal_group = 'intent' then v_actor_label || ' opened your Intent card.'
        when v_signal_group = 'repeat_visit' then v_actor_label || ' revisited your profile.'
        else null
      end
    else
      case
        when v_signal_group = 'save' then 'Someone saved your profile.'
        when v_event_type = 'intro_completed' then 'Someone finished your intro video.'
        when v_signal_group = 'intro' then 'Someone spent time with your intro video.'
        when v_signal_group = 'intent' then 'Someone opened your Intent card.'
        when v_signal_group = 'repeat_visit' then 'Someone revisited your profile.'
        else null
      end
  end;

  v_notification_metadata := jsonb_strip_nulls(jsonb_build_object(
    'type', 'profile_interest',
    'signal', v_event_type,
    'signal_group', v_signal_group,
    'audience_plan', v_target_plan,
    'detail_tier', case
      when v_target_plan = 'GOLD' then 'gold_story'
      when v_target_plan = 'SILVER' then 'silver_identity'
      else 'free_teaser'
    end,
    'identity_revealed', v_identity_revealed,
    'cta_plan', case
      when v_target_plan = 'FREE' then 'SILVER'
      when v_target_plan = 'SILVER' then 'GOLD'
      else null
    end,
    'profile_id', case when v_identity_revealed then p_viewer_profile_id end,
    'name', case when v_identity_revealed then v_actor_label end,
    'avatar_url', case when v_identity_revealed then v_viewer_avatar end,
    'route', '/profile-interest'
  ));

  v_push_payload := jsonb_strip_nulls(jsonb_build_object(
    'type', 'profile_interest',
    'signal', v_event_type,
    'signal_group', v_signal_group,
    'audience_plan', v_target_plan,
    'detail_tier', case
      when v_target_plan = 'GOLD' then 'gold_story'
      when v_target_plan = 'SILVER' then 'silver_identity'
      else 'free_teaser'
    end,
    'identity_revealed', v_identity_revealed,
    'cta_plan', case
      when v_target_plan = 'FREE' then 'SILVER'
      when v_target_plan = 'SILVER' then 'GOLD'
      else null
    end,
    'route', '/profile-interest',
    'profile_id', case when v_identity_revealed then p_viewer_profile_id end,
    'name', case when v_identity_revealed then v_actor_label end,
    'avatar_url', case when v_identity_revealed then v_viewer_avatar end
  ));

  if v_inbox_allowed and v_notification_body is not null then
    insert into public.inbox_items (
      user_id,
      type,
      actor_id,
      entity_id,
      entity_type,
      title,
      body,
      action_required,
      metadata
    )
    values (
      v_target_user_id,
      'SYSTEM',
      v_notification_actor_id,
      p_target_profile_id,
      'profile_interest',
      v_notification_title,
      v_notification_body,
      false,
      v_notification_metadata
    );

    v_delivered := true;
  end if;

  if v_push_allowed and v_push_body is not null then
    perform private.send_push_webhook(
      jsonb_build_object(
        'user_id', v_target_user_id,
        'title', v_push_title,
        'body', v_push_body,
        'data', v_push_payload
      )
    );

    v_delivered := true;
  end if;

  if v_delivered then
    insert into public.profile_interest_notification_deliveries (
      recipient_user_id,
      actor_profile_id,
      target_profile_id,
      signal_group,
      signal_type,
      audience_plan,
      dedupe_scope,
      delivered_at
    )
    values (
      v_target_user_id,
      case when v_signal_dedupe_scope = 'actor' then p_viewer_profile_id else null end,
      p_target_profile_id,
      v_signal_group,
      v_event_type,
      v_target_plan,
      v_signal_dedupe_scope,
      timezone('utc'::text, now())
    );
  end if;

  return true;
end;
$$;

revoke all on function public.rpc_log_vibes_event(uuid, uuid, text, text, integer, integer, jsonb) from public;
grant execute on function public.rpc_log_vibes_event(uuid, uuid, text, text, integer, integer, jsonb) to authenticated;

revoke all on table public.profile_interest_notification_deliveries from public, anon, authenticated;
