-- Surface-aware recommendation rotation outside Vibes.
--
-- These surfaces are intentionally slower than the Vibes deck:
--   * Intent Suggested: one stable UTC-day field.
--   * Relationship Compass: one stable UTC-day field per saved Compass version.
--   * Circle discovery: one stable UTC-day ordering (ordering only; no hidden pool).
--   * Circle Home Picks: one stable 72-hour field.
--   * Closure to Clarity: one stable seven-day field per closed request.
--
-- Supabase owns eligibility, ranking, batching, and exposure history. Clients
-- receive display fields only; private scores and rotation state remain hidden.

begin;

create table if not exists public.profile_recommendation_batches (
  viewer_profile_id uuid not null references public.profiles(id) on delete cascade,
  surface text not null,
  context_key text not null default '',
  bucket_key text not null,
  candidate_profile_id uuid not null references public.profiles(id) on delete cascade,
  rank integer not null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  primary key (viewer_profile_id, surface, context_key, bucket_key, candidate_profile_id),
  constraint profile_recommendation_batches_surface_check check (surface in (
    'intent_suggested', 'relationship_compass', 'circle_home_picks',
    'circle_discovery', 'closure_to_clarity'
  )),
  constraint profile_recommendation_batches_rank_check check (rank > 0),
  constraint profile_recommendation_batches_distinct_profiles check (
    viewer_profile_id <> candidate_profile_id
  )
);

create unique index if not exists profile_recommendation_batches_rank_uidx
  on public.profile_recommendation_batches(
    viewer_profile_id, surface, context_key, bucket_key, rank
  );
create index if not exists profile_recommendation_batches_cleanup_idx
  on public.profile_recommendation_batches(created_at);

alter table public.profile_recommendation_batches enable row level security;
revoke all on table public.profile_recommendation_batches from public, anon, authenticated;
grant all on table public.profile_recommendation_batches to service_role;

create table if not exists public.profile_recommendation_events (
  id bigint generated by default as identity primary key,
  viewer_profile_id uuid not null references public.profiles(id) on delete cascade,
  candidate_profile_id uuid not null references public.profiles(id) on delete cascade,
  surface text not null,
  context_key text not null default '',
  bucket_key text not null,
  event_type text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  constraint profile_recommendation_events_surface_check check (surface in (
    'relationship_compass', 'closure_to_clarity'
  )),
  constraint profile_recommendation_events_type_check check (event_type in (
    'impression', 'profile_opened', 'intent_opened', 'intent_sent'
  )),
  constraint profile_recommendation_events_distinct_profiles check (
    viewer_profile_id <> candidate_profile_id
  )
);

create index if not exists profile_recommendation_events_exposure_idx
  on public.profile_recommendation_events(
    viewer_profile_id, surface, candidate_profile_id, created_at desc
  ) where event_type = 'impression';
create index if not exists profile_recommendation_events_context_idx
  on public.profile_recommendation_events(
    viewer_profile_id, surface, context_key, created_at desc
  );
create unique index if not exists profile_recommendation_events_impression_uidx
  on public.profile_recommendation_events(
    viewer_profile_id, candidate_profile_id, surface, context_key, bucket_key, event_type
  ) where event_type = 'impression';

alter table public.profile_recommendation_events enable row level security;
revoke all on table public.profile_recommendation_events from public, anon, authenticated;
grant all on table public.profile_recommendation_events to service_role;

create or replace function public.rpc_log_profile_recommendation_event(
  p_surface text,
  p_candidate_profile_id uuid,
  p_event_type text default 'impression',
  p_context_key text default '',
  p_metadata jsonb default '{}'
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
set row_security = off
as $$
#variable_conflict use_column
declare
  v_viewer_id uuid;
  v_surface text := lower(btrim(coalesce(p_surface, '')));
  v_context_key text := btrim(coalesce(p_context_key, ''));
  v_bucket_key text;
  v_compass_version text;
begin
  if auth.uid() is null then
    raise exception 'unauthenticated' using errcode = '42501';
  end if;
  if v_surface not in ('relationship_compass', 'closure_to_clarity') then
    raise exception 'invalid_recommendation_surface' using errcode = '22023';
  end if;
  if p_event_type not in ('impression', 'profile_opened', 'intent_opened', 'intent_sent') then
    raise exception 'invalid_recommendation_event' using errcode = '22023';
  end if;

  select profile.id,
         substring(md5(coalesce(profile.relationship_compass ->> 'updatedAt', 'initial')) from 1 for 12)
    into v_viewer_id, v_compass_version
  from public.profiles profile
  where profile.user_id = auth.uid()
    and profile.deleted_at is null
    and profile.account_state = 'active'
  limit 1;

  if v_viewer_id is null or p_candidate_profile_id is null
    or p_candidate_profile_id = v_viewer_id then
    return false;
  end if;
  if not public.is_romantically_eligible(
    v_viewer_id, p_candidate_profile_id, 'global', null
  ) then
    return false;
  end if;

  if v_surface = 'relationship_compass' then
    v_context_key := '';
    v_bucket_key := to_char(timezone('utc', now()), 'YYYY-MM-DD') || ':' || v_compass_version;
  else
    if v_context_key = '' or not exists (
      select 1
      from public.intent_requests request_row
      where request_row.id::text = v_context_key
        and (request_row.actor_id = v_viewer_id or request_row.recipient_id = v_viewer_id)
    ) then
      raise exception 'invalid_recommendation_context' using errcode = '42501';
    end if;
    v_bucket_key := floor(extract(epoch from timezone('utc', now())) / 604800)::bigint::text;
  end if;

  if p_event_type = 'impression' and exists (
    select 1
    from public.profile_recommendation_events event_row
    where event_row.viewer_profile_id = v_viewer_id
      and event_row.candidate_profile_id = p_candidate_profile_id
      and event_row.surface = v_surface
      and event_row.context_key = v_context_key
      and event_row.bucket_key = v_bucket_key
      and event_row.event_type = 'impression'
  ) then
    return true;
  end if;

  insert into public.profile_recommendation_events (
    viewer_profile_id, candidate_profile_id, surface, context_key,
    bucket_key, event_type, metadata
  ) values (
    v_viewer_id, p_candidate_profile_id, v_surface, v_context_key,
    v_bucket_key, p_event_type,
    jsonb_strip_nulls(jsonb_build_object(
      'position', coalesce(p_metadata, '{}') -> 'position',
      'lane', coalesce(p_metadata, '{}') -> 'lane'
    ))
  ) on conflict do nothing;
  return true;
end;
$$;

revoke all on function public.rpc_log_profile_recommendation_event(text, uuid, text, text, jsonb)
  from public, anon;
grant execute on function public.rpc_log_profile_recommendation_event(text, uuid, text, text, jsonb)
  to authenticated;

create or replace function public.rpc_cleanup_profile_recommendation_rotation(
  p_retention interval default interval '45 days'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
set row_security = off
as $$
declare
  v_retention interval := greatest(coalesce(p_retention, interval '45 days'), interval '14 days');
  v_batches_deleted integer := 0;
  v_events_deleted integer := 0;
begin
  if current_user not in ('postgres', 'supabase_admin')
    and coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;

  delete from public.profile_recommendation_batches batch
  where batch.created_at < timezone('utc', now()) - v_retention;
  get diagnostics v_batches_deleted = row_count;

  delete from public.profile_recommendation_events event_row
  where event_row.created_at < timezone('utc', now()) - v_retention;
  get diagnostics v_events_deleted = row_count;

  return jsonb_build_object(
    'batches_deleted', v_batches_deleted,
    'events_deleted', v_events_deleted,
    'retention_seconds', extract(epoch from v_retention)::bigint,
    'completed_at', timezone('utc', now())
  );
end;
$$;

revoke all on function public.rpc_cleanup_profile_recommendation_rotation(interval)
  from public, anon, authenticated;
grant execute on function public.rpc_cleanup_profile_recommendation_rotation(interval)
  to service_role;

do $$
declare
  v_job_id bigint;
begin
  if to_regprocedure('cron.schedule(text,text,text)') is null then
    raise notice 'pg_cron is unavailable; schedule recommendation rotation cleanup externally';
    return;
  end if;

  for v_job_id in
    select jobid from cron.job
    where jobname = 'profile-recommendation-rotation-cleanup'
  loop
    perform cron.unschedule(v_job_id);
  end loop;

  perform cron.schedule(
    'profile-recommendation-rotation-cleanup',
    '41 3 * * *',
    'select public.rpc_cleanup_profile_recommendation_rotation(interval ''45 days'');'
  );
exception
  when insufficient_privilege then
    raise notice 'Unable to schedule recommendation cleanup; configure it with service-role scheduling';
  when undefined_table or undefined_function then
    raise notice 'pg_cron metadata is unavailable; configure recommendation cleanup externally';
end;
$$;

create or replace function public.rpc_get_profile_recommendation_rotation_health()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_catalog
set row_security = off
as $$
  select jsonb_build_object(
    'generated_at', timezone('utc', now()),
    'batches_24h', coalesce((
      select jsonb_object_agg(summary.surface, summary.total)
      from (
        select batch.surface, count(distinct (
          batch.viewer_profile_id,
          batch.context_key,
          batch.bucket_key
        ))::integer as total
        from public.profile_recommendation_batches batch
        where batch.created_at >= timezone('utc', now()) - interval '24 hours'
        group by batch.surface
      ) summary
    ), '{}'::jsonb),
    'candidates_batched_24h', coalesce((
      select jsonb_object_agg(summary.surface, summary.total)
      from (
        select batch.surface, count(*)::integer as total
        from public.profile_recommendation_batches batch
        where batch.created_at >= timezone('utc', now()) - interval '24 hours'
        group by batch.surface
      ) summary
    ), '{}'::jsonb),
    'impressions_24h', coalesce((
      select jsonb_object_agg(summary.surface, summary.total)
      from (
        select event_row.surface, count(*)::integer as total
        from public.profile_recommendation_events event_row
        where event_row.event_type = 'impression'
          and event_row.created_at >= timezone('utc', now()) - interval '24 hours'
        group by event_row.surface
      ) summary
    ), '{}'::jsonb),
    'oldest_batch_created_at', (
      select min(batch.created_at) from public.profile_recommendation_batches batch
    )
  );
$$;

revoke all on function public.rpc_get_profile_recommendation_rotation_health()
  from public, anon, authenticated;
grant execute on function public.rpc_get_profile_recommendation_rotation_health()
  to service_role;

notify pgrst, 'reload schema';

commit;
