-- Connection-capacity telemetry and transition alerts for operations admins.

begin;

create table if not exists public.database_capacity_samples (
  sampled_at timestamptz primary key default timezone('utc', now()),
  connections integer not null,
  usable_connections integer not null,
  utilization_percent numeric(5,2) not null,
  level text not null check (level in ('healthy', 'warning', 'high', 'critical')),
  by_application jsonb not null default '{}'
);

create index if not exists database_capacity_samples_level_time_idx
  on public.database_capacity_samples(level, sampled_at desc);

create table if not exists public.database_capacity_alerts (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('healthy', 'warning', 'high', 'critical')),
  connections integer not null,
  usable_connections integer not null,
  utilization_percent numeric(5,2) not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists private.database_capacity_monitor_state (
  id boolean primary key default true check (id),
  level text not null default 'healthy',
  updated_at timestamptz not null default timezone('utc', now())
);
insert into private.database_capacity_monitor_state(id) values (true)
on conflict (id) do nothing;

alter table public.database_capacity_samples enable row level security;
alter table public.database_capacity_alerts enable row level security;
revoke all on public.database_capacity_samples from public, anon, authenticated;
revoke all on public.database_capacity_alerts from public, anon, authenticated;
grant all on public.database_capacity_samples to service_role;
grant all on public.database_capacity_alerts to service_role;

create or replace function private.capture_database_capacity_v1()
returns void
language plpgsql
security definer
set search_path = public, private, pg_catalog
set row_security = off
as $$
declare
  v_connections integer;
  v_usable integer := current_setting('max_connections')::integer
    - current_setting('superuser_reserved_connections')::integer;
  v_percent numeric(5,2);
  v_level text;
  v_previous_level text;
  v_by_application jsonb;
  v_text text;
begin
  select count(*)::integer,
    coalesce(jsonb_object_agg(summary.application, summary.connections), '{}')
  into v_connections, v_by_application
  from (
    select coalesce(nullif(application_name, ''), '(unknown)') as application,
      count(*)::integer as connections
    from pg_stat_activity
    where backend_type = 'client backend'
    group by coalesce(nullif(application_name, ''), '(unknown)')
  ) summary;

  v_percent := round((v_connections::numeric / greatest(v_usable, 1)) * 100, 2);
  v_level := case
    when v_percent >= 90 then 'critical'
    when v_percent >= 80 then 'high'
    when v_percent >= 70 then 'warning'
    else 'healthy'
  end;

  insert into public.database_capacity_samples(
    connections, usable_connections, utilization_percent, level, by_application
  ) values (v_connections, v_usable, v_percent, v_level, v_by_application);

  delete from public.database_capacity_samples
  where sampled_at < timezone('utc', now()) - interval '30 days';

  delete from public.database_capacity_alerts
  where created_at < timezone('utc', now()) - interval '180 days';

  select state.level into v_previous_level
  from private.database_capacity_monitor_state state
  where state.id = true
  for update;

  if v_level is distinct from v_previous_level then
    update private.database_capacity_monitor_state
    set level = v_level, updated_at = timezone('utc', now())
    where id = true;

    insert into public.database_capacity_alerts(
      level, connections, usable_connections, utilization_percent
    ) values (v_level, v_connections, v_usable, v_percent);

    v_text := case v_level
      when 'critical' then 'Database connections reached the critical 90% threshold.'
      when 'high' then 'Database connections reached the high 80% threshold.'
      when 'warning' then 'Database connections reached the warning 70% threshold.'
      else 'Database connection capacity has recovered below 70%.'
    end;

    insert into public.system_messages(
      user_id, peer_user_id, event_type, text, metadata
    )
    select admin.user_id, admin.user_id, 'database_capacity_alert', v_text,
      jsonb_build_object(
        'role', 'operations',
        'level', v_level,
        'connections', v_connections,
        'usable_connections', v_usable,
        'utilization_percent', v_percent
      )
    from public.internal_admins admin
    where admin.role in ('operations', 'super_admin');
  end if;
end;
$$;

revoke all on function private.capture_database_capacity_v1() from public, anon, authenticated;
grant execute on function private.capture_database_capacity_v1() to service_role;

create or replace function public.rpc_admin_get_database_capacity_v1(p_limit integer default 120)
returns table (
  sampled_at timestamptz, connections integer, usable_connections integer,
  utilization_percent numeric, level text, by_application jsonb
)
language plpgsql
security definer
set search_path = public, pg_catalog
set row_security = off
as $$
begin
  if not public.is_admin_user(auth.uid()) then
    raise exception 'admin_required' using errcode = '42501';
  end if;
  return query
  select sample.sampled_at, sample.connections, sample.usable_connections,
    sample.utilization_percent, sample.level, sample.by_application
  from public.database_capacity_samples sample
  order by sample.sampled_at desc
  limit greatest(1, least(coalesce(p_limit, 120), 1440));
end;
$$;

revoke all on function public.rpc_admin_get_database_capacity_v1(integer) from public, anon;
grant execute on function public.rpc_admin_get_database_capacity_v1(integer) to authenticated, service_role;

do $$
declare
  existing_job bigint;
begin
  if to_regprocedure('cron.schedule(text,text,text)') is null then
    raise notice 'pg_cron unavailable; database capacity monitoring was not scheduled';
    return;
  end if;
  select jobid into existing_job from cron.job where jobname = 'database-capacity-monitor-v1';
  if existing_job is not null then perform cron.unschedule(existing_job); end if;
  perform cron.schedule(
    'database-capacity-monitor-v1', '* * * * *',
    'select private.capture_database_capacity_v1()'
  );
end $$;

notify pgrst, 'reload schema';
commit;
