-- Phase: contextual Circle discovery.
-- Supabase remains the authority for romantic eligibility and ranking. Circle
-- membership is community consent only; dating consent remains private in
-- circle_dating_preferences.

begin;

create table if not exists public.circle_member_context (
  circle_id uuid not null references public.circles(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  reasons text[] not null default '{}',
  priorities text[] not null default '{}',
  completed_at timestamptz,
  skipped_at timestamptz,
  version integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (circle_id, profile_id),
  constraint circle_member_context_reasons_limit check (cardinality(reasons) <= 3),
  constraint circle_member_context_priorities_limit check (cardinality(priorities) <= 3)
);

alter table public.circle_member_context enable row level security;
drop policy if exists circle_member_context_select_own on public.circle_member_context;
create policy circle_member_context_select_own
on public.circle_member_context for select to authenticated
using (exists (
  select 1 from public.profiles viewer
  where viewer.id = circle_member_context.profile_id
    and viewer.user_id = auth.uid()
    and viewer.deleted_at is null
));
revoke all on table public.circle_member_context from public, anon;
grant select on table public.circle_member_context to authenticated;

-- Private operational telemetry. No profile preference, eligibility result, or
-- raw ranking score is exposed to clients.
create table if not exists public.circle_discovery_events (
  id bigint generated by default as identity primary key,
  circle_id uuid not null references public.circles(id) on delete cascade,
  viewer_profile_id uuid not null references public.profiles(id) on delete cascade,
  target_profile_id uuid references public.profiles(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  constraint circle_discovery_events_type_check check (event_type in (
    'entry_opened', 'entry_completed', 'entry_skipped', 'dating_opted_in',
    'candidate_impression', 'profile_opened', 'candidate_passed',
    'intent_opened', 'intent_sent'
  )),
  constraint circle_discovery_events_distinct_profiles check (
    target_profile_id is null or target_profile_id <> viewer_profile_id
  )
);
alter table public.circle_discovery_events enable row level security;
revoke all on table public.circle_discovery_events from public, anon, authenticated;
create index if not exists circle_discovery_events_aggregate_idx
  on public.circle_discovery_events(circle_id, event_type, created_at desc);
create index if not exists circle_discovery_events_exposure_idx
  on public.circle_discovery_events(viewer_profile_id, target_profile_id, created_at desc)
  where event_type = 'candidate_impression';

create or replace function public.rpc_get_my_circle_member_context(p_circle_id uuid)
returns jsonb
language plpgsql stable security definer
set search_path = public, pg_catalog set row_security = off
as $$
declare
  v_profile_id uuid;
  v_context public.circle_member_context%rowtype;
  v_is_member boolean;
begin
  if auth.uid() is null then
    raise exception 'unauthenticated' using errcode = '42501';
  end if;
  select id into v_profile_id from public.profiles
  where user_id = auth.uid() and deleted_at is null limit 1;
  select exists (
    select 1 from public.circle_members
    where circle_id = p_circle_id and profile_id = v_profile_id
      and status = 'active' and is_visible is not false
  ) into v_is_member;
  select * into v_context from public.circle_member_context
  where circle_id = p_circle_id and profile_id = v_profile_id;
  return jsonb_build_object(
    'is_member', v_is_member,
    'reasons', coalesce(v_context.reasons, '{}'),
    'priorities', coalesce(v_context.priorities, '{}'),
    'completed_at', v_context.completed_at,
    'skipped_at', v_context.skipped_at,
    'needs_entry', v_is_member and v_context.completed_at is null and v_context.skipped_at is null
  );
end;
$$;

create or replace function public.rpc_set_my_circle_member_context(
  p_circle_id uuid,
  p_reasons text[] default '{}',
  p_priorities text[] default '{}',
  p_skip boolean default false
)
returns jsonb
language plpgsql security definer
set search_path = public, pg_catalog set row_security = off
as $$
declare
  v_profile_id uuid;
  v_reasons text[];
  v_priorities text[];
  v_row public.circle_member_context%rowtype;
begin
  if auth.uid() is null then
    raise exception 'unauthenticated' using errcode = '42501';
  end if;
  select id into v_profile_id from public.profiles
  where user_id = auth.uid() and deleted_at is null and account_state = 'active'
  limit 1;
  if v_profile_id is null or not exists (
    select 1 from public.circle_members
    where circle_id = p_circle_id and profile_id = v_profile_id
      and status = 'active' and is_visible is not false
  ) then
    raise exception 'circle_membership_required' using errcode = '42501';
  end if;

  select coalesce(array_agg(value order by ordinal), '{}') into v_reasons
  from (
    select distinct on (lower(btrim(item))) left(btrim(item), 48) value, ordinal
    from unnest(coalesce(p_reasons, '{}')) with ordinality valueset(item, ordinal)
    where nullif(btrim(item), '') is not null
    order by lower(btrim(item)), ordinal
    limit 3
  ) clean;
  select coalesce(array_agg(value order by ordinal), '{}') into v_priorities
  from (
    select distinct on (lower(btrim(item))) left(btrim(item), 48) value, ordinal
    from unnest(coalesce(p_priorities, '{}')) with ordinality valueset(item, ordinal)
    where nullif(btrim(item), '') is not null
    order by lower(btrim(item)), ordinal
    limit 3
  ) clean;

  insert into public.circle_member_context (
    circle_id, profile_id, reasons, priorities, completed_at, skipped_at, updated_at
  ) values (
    p_circle_id, v_profile_id,
    case when p_skip then '{}' else v_reasons end,
    case when p_skip then '{}' else v_priorities end,
    case when p_skip then null else timezone('utc', now()) end,
    case when p_skip then timezone('utc', now()) else null end,
    timezone('utc', now())
  )
  on conflict (circle_id, profile_id) do update set
    reasons = excluded.reasons,
    priorities = excluded.priorities,
    completed_at = excluded.completed_at,
    skipped_at = excluded.skipped_at,
    updated_at = excluded.updated_at
  returning * into v_row;

  insert into public.circle_discovery_events(circle_id, viewer_profile_id, event_type)
  values (p_circle_id, v_profile_id, case when p_skip then 'entry_skipped' else 'entry_completed' end);

  return jsonb_build_object(
    'is_member', true, 'reasons', v_row.reasons, 'priorities', v_row.priorities,
    'completed_at', v_row.completed_at, 'skipped_at', v_row.skipped_at,
    'needs_entry', false
  );
end;
$$;

-- Internal, central evaluator. It deliberately returns only a boolean. Failure
-- details stay inside the authority boundary.
create or replace function public.is_romantically_eligible(
  p_actor_profile_id uuid,
  p_target_profile_id uuid,
  p_context_type text default 'global',
  p_context_id uuid default null
)
returns boolean
language sql stable security definer
set search_path = public, pg_catalog set row_security = off
as $$
  select exists (
    select 1
    from public.profiles actor
    join public.profiles target on target.id = p_target_profile_id
    where actor.id = p_actor_profile_id
      and actor.id <> target.id
      and actor.user_id is not null and target.user_id is not null
      and actor.deleted_at is null and target.deleted_at is null
      and actor.account_state = 'active' and target.account_state = 'active'
      and coalesce(actor.is_active, true) and coalesce(target.is_active, true)
      and coalesce(actor.profile_completed, false) and coalesce(target.profile_completed, false)
      and coalesce(actor.discoverable_in_vibes, true) and coalesce(target.discoverable_in_vibes, true)
      and coalesce(actor.matchmaking_mode, false) = false
      and coalesce(target.matchmaking_mode, false) = false
      and (
        upper(btrim(coalesce(actor.gender::text, ''))) not in ('MALE', 'FEMALE')
        or upper(btrim(coalesce(target.gender::text, ''))) not in ('MALE', 'FEMALE')
        or upper(btrim(actor.gender::text)) <> upper(btrim(target.gender::text))
      )
      and (actor.age_preference_confirmed_at is null or actor.min_age_interest is null or target.age is null or target.age >= actor.min_age_interest)
      and (actor.age_preference_confirmed_at is null or actor.max_age_interest is null or target.age is null or target.age <= actor.max_age_interest)
      and (target.age_preference_confirmed_at is null or target.min_age_interest is null or actor.age is null or actor.age >= target.min_age_interest)
      and (target.age_preference_confirmed_at is null or target.max_age_interest is null or actor.age is null or actor.age <= target.max_age_interest)
      and not exists (
        select 1 from public.blocks blocked
        where (blocked.blocker_id = actor.user_id and blocked.blocked_id = target.user_id)
           or (blocked.blocker_id = target.user_id and blocked.blocked_id = actor.user_id)
      )
      and (
        lower(coalesce(p_context_type, 'global')) <> 'circle'
        or (
          p_context_id is not null
          and exists (
            select 1 from public.circle_members am
            join public.circle_dating_preferences ap
              on ap.circle_id = am.circle_id and ap.profile_id = am.profile_id
            where am.circle_id = p_context_id and am.profile_id = actor.id
              and am.status = 'active' and am.is_visible is not false
              and ap.opted_in and ap.open_to_intents
          )
          and exists (
            select 1 from public.circle_members tm
            join public.circle_dating_preferences tp
              on tp.circle_id = tm.circle_id and tp.profile_id = tm.profile_id
            where tm.circle_id = p_context_id and tm.profile_id = target.id
              and tm.status = 'active' and tm.is_visible is not false
              and tp.opted_in and tp.open_to_intents
          )
        )
      )
  );
$$;
revoke all on function public.is_romantically_eligible(uuid, uuid, text, uuid) from public, anon, authenticated;

create or replace function public.rpc_get_romantic_eligibility(
  p_target_profile_id uuid,
  p_context_type text default 'global',
  p_context_id uuid default null
)
returns jsonb
language plpgsql stable security definer
set search_path = public, pg_catalog set row_security = off
as $$
declare v_actor_id uuid; v_eligible boolean;
begin
  if auth.uid() is null then raise exception 'unauthenticated' using errcode = '42501'; end if;
  select id into v_actor_id from public.profiles where user_id = auth.uid() and deleted_at is null limit 1;
  v_eligible := public.is_romantically_eligible(v_actor_id, p_target_profile_id, p_context_type, p_context_id);
  return jsonb_build_object(
    'eligible', v_eligible,
    'can_like', v_eligible,
    'can_signal', v_eligible,
    'can_intent', v_eligible
  );
end;
$$;

create or replace function public.enforce_romantic_eligibility()
returns trigger
language plpgsql security definer
set search_path = public, pg_catalog set row_security = off
as $$
declare v_actor uuid; v_target uuid; v_context text := 'global'; v_context_id uuid;
begin
  if tg_table_name = 'intent_requests' then
    v_actor := new.actor_id; v_target := new.recipient_id;
    if new.metadata ->> 'source' = 'circles' then
      v_context := 'circle';
      begin v_context_id := nullif(new.metadata ->> 'circle_id', '')::uuid;
      exception when invalid_text_representation then v_context_id := null; end;
    end if;
  elsif tg_table_name = 'profile_signal_gestures' then
    v_actor := new.sender_profile_id; v_target := new.receiver_profile_id;
  elsif tg_table_name = 'swipes' then
    if upper(new.action::text) not in ('LIKE', 'SUPERLIKE') then return new; end if;
    v_actor := new.swiper_id; v_target := new.target_id;
  else
    return new;
  end if;
  if not public.is_romantically_eligible(v_actor, v_target, v_context, v_context_id) then
    raise exception 'dating_not_eligible' using errcode = 'P0001';
  end if;
  return new;
end;
$$;
revoke all on function public.enforce_romantic_eligibility() from public, anon, authenticated;

drop trigger if exists enforce_intent_romantic_eligibility on public.intent_requests;
create trigger enforce_intent_romantic_eligibility before insert on public.intent_requests
for each row execute function public.enforce_romantic_eligibility();
drop trigger if exists enforce_signal_romantic_eligibility on public.profile_signal_gestures;
create trigger enforce_signal_romantic_eligibility before insert on public.profile_signal_gestures
for each row execute function public.enforce_romantic_eligibility();
drop trigger if exists enforce_swipe_romantic_eligibility on public.swipes;
create trigger enforce_swipe_romantic_eligibility before insert or update of action on public.swipes
for each row execute function public.enforce_romantic_eligibility();

create or replace function public.rpc_log_circle_discovery_event(
  p_circle_id uuid,
  p_event_type text,
  p_target_profile_id uuid default null,
  p_metadata jsonb default '{}'
)
returns boolean
language plpgsql security definer
set search_path = public, pg_catalog set row_security = off
as $$
declare v_viewer_id uuid;
begin
  if p_event_type not in (
    'entry_opened', 'dating_opted_in', 'candidate_impression', 'profile_opened',
    'candidate_passed', 'intent_opened', 'intent_sent'
  ) then raise exception 'invalid_circle_discovery_event' using errcode = '22023'; end if;
  select id into v_viewer_id from public.profiles where user_id = auth.uid() and deleted_at is null limit 1;
  if v_viewer_id is null or not exists (
    select 1 from public.circle_members where circle_id = p_circle_id
      and profile_id = v_viewer_id and status = 'active'
  ) then raise exception 'circle_membership_required' using errcode = '42501'; end if;
  insert into public.circle_discovery_events(circle_id, viewer_profile_id, target_profile_id, event_type, metadata)
  values (p_circle_id, v_viewer_id, p_target_profile_id, p_event_type,
    jsonb_strip_nulls(jsonb_build_object(
      'surface', coalesce(p_metadata, '{}') -> 'surface',
      'position', coalesce(p_metadata, '{}') -> 'position',
      'reason_category', coalesce(p_metadata, '{}') -> 'reason_category'
    )));
  return true;
end;
$$;

-- Central v1 weights: global fit 70%, Circle affinity 30%. Global fit is
-- normalized over available signals: intent .22, values .18, lifestyle .14,
-- interests .12, location .10, age .08, culture .07, recency .05, quality .04.
create or replace function public.rpc_get_circle_dating_candidates(
  p_circle_id uuid,
  p_limit integer default 20
)
returns table (
  profile_id uuid, full_name text, age integer, avatar_url text, city text,
  country text, looking_for text, verification_level integer, reason text
)
language plpgsql stable security definer
set search_path = public, pg_catalog set row_security = off
as $$
#variable_conflict use_column
declare v_profile_id uuid;
begin
  select id into v_profile_id from public.profiles
  where user_id = auth.uid() and deleted_at is null and account_state = 'active' limit 1;
  if v_profile_id is null or not exists (
    select 1 from public.circle_dating_preferences p
    join public.circle_members m on m.circle_id = p.circle_id and m.profile_id = p.profile_id
    where p.circle_id = p_circle_id and p.profile_id = v_profile_id and p.opted_in
      and p.open_to_intents and m.status = 'active' and m.is_visible is not false
  ) then return; end if;

  return query
  with viewer as (
    select p.*, c.reasons context_reasons, c.priorities context_priorities
    from public.profiles p
    left join public.circle_member_context c on c.circle_id = p_circle_id and c.profile_id = p.id
    where p.id = v_profile_id
  ), eligible as (
    select candidate.*,
      coalesce(shared.count, 0)::integer shared_count,
      coalesce(exposure.count, 0)::integer exposure_count,
      target_context.reasons target_reasons,
      target_context.priorities target_priorities
    from viewer
    join public.circle_members member on member.circle_id = p_circle_id
      and member.profile_id <> viewer.id and member.status = 'active' and member.is_visible is not false
    join public.circle_dating_preferences preference on preference.circle_id = member.circle_id
      and preference.profile_id = member.profile_id and preference.opted_in and preference.open_to_intents
    join public.profiles candidate on candidate.id = member.profile_id
    left join public.circle_member_context target_context
      on target_context.circle_id = p_circle_id and target_context.profile_id = candidate.id
    left join lateral (
      select count(*) count from public.profile_interests ci
      join public.profile_interests vi on vi.interest_id = ci.interest_id and vi.profile_id = viewer.id
      where ci.profile_id = candidate.id
    ) shared on true
    left join lateral (
      select count(*) count from public.circle_discovery_events event
      where event.viewer_profile_id = viewer.id and event.target_profile_id = candidate.id
        and event.event_type = 'candidate_impression'
        and event.created_at >= timezone('utc', now()) - interval '7 days'
    ) exposure on true
    where public.is_romantically_eligible(viewer.id, candidate.id, 'circle', p_circle_id)
      and not exists (
        select 1 from public.matches m where lower(coalesce(m.status::text, '')) in ('pending','accepted')
          and ((m.user1_id = viewer.id and m.user2_id = candidate.id) or (m.user2_id = viewer.id and m.user1_id = candidate.id))
      )
      and not exists (
        select 1 from public.intent_requests r where r.status = 'pending' and r.expires_at > timezone('utc', now())
          and ((r.actor_id = viewer.id and r.recipient_id = candidate.id) or (r.recipient_id = viewer.id and r.actor_id = candidate.id))
      )
      and not exists (
        select 1 from public.circle_dating_passes pass where pass.circle_id = p_circle_id
          and pass.actor_profile_id = viewer.id and pass.target_profile_id = candidate.id
          and pass.created_at > timezone('utc', now()) - interval '14 days'
      )
  ), signals as (
    select eligible.*, viewer.looking_for viewer_looking_for, viewer.religion viewer_religion,
      viewer.smoking viewer_smoking, viewer.drinking viewer_drinking,
      viewer.wants_children viewer_wants_children, viewer.love_language viewer_love_language,
      viewer.city viewer_city, viewer.current_country viewer_country, viewer.tribe viewer_tribe,
      viewer.age viewer_age, viewer.context_reasons, viewer.context_priorities,
      case when nullif(btrim(viewer.looking_for),'') is not null and nullif(btrim(eligible.looking_for),'') is not null then 0.22 else 0 end aw_intent,
      case when viewer.religion is not null and eligible.religion is not null then 0.18 else 0 end aw_values,
      case when coalesce(viewer.smoking,viewer.drinking,viewer.wants_children,viewer.love_language) is not null
             and coalesce(eligible.smoking,eligible.drinking,eligible.wants_children,eligible.love_language) is not null then 0.14 else 0 end aw_lifestyle,
      case when eligible.shared_count > 0 then 0.12 else 0 end aw_interests,
      case when coalesce(viewer.city,viewer.current_country) is not null and coalesce(eligible.city,eligible.current_country) is not null then 0.10 else 0 end aw_location,
      case when viewer.age is not null and eligible.age is not null then 0.08 else 0 end aw_age,
      case when coalesce(viewer.tribe,viewer.origin_country) is not null and coalesce(eligible.tribe,eligible.origin_country) is not null then 0.07 else 0 end aw_culture,
      case when eligible.last_active is not null then 0.05 else 0 end aw_recency,
      0.04::numeric aw_quality
    from eligible cross join viewer
  ), scored as (
    select signals.*,
      (
        aw_intent * case when lower(btrim(viewer_looking_for)) = lower(btrim(looking_for)) then 1 else .35 end
        + aw_values * case when viewer_religion = religion then 1 else .25 end
        + aw_lifestyle * ((
            (case when viewer_smoking is not null and smoking is not null and lower(viewer_smoking)=lower(smoking) then 1 else 0 end) +
            (case when viewer_drinking is not null and drinking is not null and lower(viewer_drinking)=lower(drinking) then 1 else 0 end) +
            (case when viewer_wants_children is not null and wants_children is not null and lower(viewer_wants_children)=lower(wants_children) then 1 else 0 end) +
            (case when viewer_love_language is not null and love_language is not null and lower(viewer_love_language)=lower(love_language) then 1 else 0 end)
          )::numeric / 4)
        + aw_interests * least(shared_count::numeric / 3, 1)
        + aw_location * case when lower(coalesce(viewer_city,''))=lower(coalesce(city,'')) and city is not null then 1 when lower(coalesce(viewer_country,''))=lower(coalesce(current_country,'')) then .65 else .15 end
        + aw_age * greatest(0, 1 - abs(viewer_age-age)::numeric / 25)
        + aw_culture * case when lower(coalesce(viewer_tribe,''))=lower(coalesce(tribe,'')) and tribe is not null then 1 else .4 end
        + aw_recency * case when last_active >= timezone('utc',now())-interval '24 hours' then 1 when last_active >= timezone('utc',now())-interval '7 days' then .6 else .2 end
        + aw_quality * least((coalesce(verification_level,0)::numeric/3) + case when nullif(btrim(bio),'') is not null then .25 else 0 end, 1)
      ) / nullif(aw_intent+aw_values+aw_lifestyle+aw_interests+aw_location+aw_age+aw_culture+aw_recency+aw_quality,0) global_score,
      least(1, (
        case when context_priorities && coalesce(target_priorities,'{}') then .45 else 0 end +
        case when context_reasons && coalesce(target_reasons,'{}') then .25 else 0 end +
        least(shared_count::numeric/3,1)*.20 +
        case when lower(coalesce(viewer_city,''))=lower(coalesce(city,'')) and city is not null then .10 else 0 end
      )) affinity_score
    from signals
  ), mixed as (
    select scored.*,
      ((.70*global_score)+(.30*affinity_score))::numeric base_score,
      mod(get_byte(decode(md5(v_profile_id::text || id::text || current_date::text),'hex'),0),10) mix_bucket,
      (get_byte(decode(md5(id::text || v_profile_id::text || current_date::text),'hex'),1)::numeric/255) exploration_value
    from scored
  )
  select id, coalesce(nullif(btrim(full_name),''),'Circle member'), age, avatar_url, city,
    current_country, looking_for, coalesce(verification_level,0),
    concat_ws(' · ', 'Shared Circle',
      case when shared_count > 0 then shared_count::text || case when shared_count=1 then ' shared interest' else ' shared interests' end end,
      case when context_priorities && coalesce(target_priorities,'{}') then 'Similar priorities' end,
      case when last_active >= timezone('utc',now())-interval '24 hours' then 'Active recently' end)
  from mixed
  order by
    case
      -- Deterministic batch policy: 70% relevance, 20% freshness/exposure,
      -- 10% bounded exploration. Hard eligibility is already applied above.
      when mix_bucket < 7 then base_score - least(exposure_count,4)*.018
      when mix_bucket < 9 then (.82*base_score)
        + (.18*case when last_active >= timezone('utc',now())-interval '24 hours' then 1 when last_active >= timezone('utc',now())-interval '7 days' then .55 else .15 end)
        - least(exposure_count,4)*.03
      else (.72*base_score)+(.28*exploration_value)-least(exposure_count,4)*.02
    end desc,
    last_active desc nulls last, id
  limit greatest(1,least(coalesce(p_limit,20),40));
end;
$$;

revoke all on function public.rpc_get_my_circle_member_context(uuid) from public, anon;
revoke all on function public.rpc_set_my_circle_member_context(uuid, text[], text[], boolean) from public, anon;
revoke all on function public.rpc_get_romantic_eligibility(uuid, text, uuid) from public, anon;
revoke all on function public.rpc_log_circle_discovery_event(uuid, text, uuid, jsonb) from public, anon;
grant execute on function public.rpc_get_my_circle_member_context(uuid) to authenticated;
grant execute on function public.rpc_set_my_circle_member_context(uuid, text[], text[], boolean) to authenticated;
grant execute on function public.rpc_get_romantic_eligibility(uuid, text, uuid) to authenticated;
grant execute on function public.rpc_log_circle_discovery_event(uuid, text, uuid, jsonb) to authenticated;

commit;
